import DesignGallery from '../DesignGallery';
import {ProductIcon} from '../ui/ProductIcon';
import {idTags as tagsService} from '../data/idTagsBackend';
import {sorted,tagAwaitingSize,validConfiguredTag,tagTypeAvailable,selectConfiguredShape,tagSnapshot,type TagsConfig} from '../domain/idTags';
import {closures as closureService} from '../data/closuresBackend';
import {availableClosures,closureName,validClosure,type Closure} from '../domain/closures';
import {useSync} from '../ui/useSync';
import AttachmentThumbnail from '../AttachmentThumbnail';
import {errorMessage,normalizeError} from '../application/errors';
import {getAvailableWidths,getAvailableDesigns,getAvailableTagSizes,selectTagShape,validateCollar} from '../domain/rules';
import {ProgressBar,StepHeader,OptionGrid,IconOption,NavigationActions} from '../ui/ConfiguratorParts';
import {canContinue,getCurrentStep,getNextStep,getPreviousStep,getProgress,isContinueDisabled,stepIds,stepsConfig} from './steps';
import Reveal from '../Reveal';
import PersonalityOptions from '../PersonalityOptions';
import {selectPersonalization} from '../domain/personalization';
import TagExtraDetails from '../TagExtraDetails';
import {extraEntries} from '../domain/extras';
import {tagModels} from '../domain/tags';
import {useEffect,useRef,useState} from 'react';
import {addItem,editItem,removeItem,restore,saveItem,DRAFT_KEY} from './state';
import {blankDraft,blankItem,changeSize,compatible,sizes,uuid,type Design,type Draft,type FontRecord,type Item,type Locale,type Order} from '../domain/model';
import {confirmation,getConfirmationCheckpoint,clearConfirmationCheckpoint,discard,loadCatalog,mode,upload} from '../data/backend';
import {DesignImage,Modal,OrderDetail,ConfirmationDate} from '../components';
import {translator,type TextKey} from '../i18n';
import LetteringSelector from '../LetteringSelector';
import CollarReview from '../CollarReview';
import DesignPreview from '../DesignPreview';

import CollapsibleCollar from '../CollapsibleCollar';
const itemPurposeDefault:'drawing'|'dog_photo'|'none'|'decoration'='none';
export default function Configurator({locale,onAdvance}:{locale:Locale;onAdvance?:()=>void}){
 const t=translator(locale),[draft,setDraft]=useState<Draft>(restore),[designs,setDesigns]=useState<Design[]>([]),[fonts,setFonts]=useState<FontRecord[]>([]),[catalogState,setCatalogState]=useState<'loading'|'ready'|'error'>('loading'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'woven'|'printed'>('woven'),[zoom,setZoom]=useState<Design|null>(null),[guide,setGuide]=useState(false),[busy,setBusy]=useState(false),[uploadState,setUploadState]=useState(''),[uploadError,setUploadError]=useState(''),[order,setOrder]=useState<Order|null>(null);
 const [recovering,setRecovering]=useState(()=>!!getConfirmationCheckpoint()),[confirmationPending,setConfirmationPending]=useState(()=>getConfirmationCheckpoint()?.state==='pending');
 const [confirmationConflict,setConfirmationConflict]=useState(false);
 const unrecoveredConfirmation=getConfirmationCheckpoint()?.state==='confirmed'&&!order;
 const confirmedAt=useRef(0);
 const lock=useRef(false),input=useRef<HTMLInputElement>(null),heading=useRef<HTMLHeadingElement>(null),fileInput=useRef<HTMLInputElement>(null),retryFile=useRef<File|null>(null),retryPurpose=useRef(itemPurposeDefault);
 const [closures,setClosures]=useState<Closure[]>([]),[closuresReady,setClosuresReady]=useState(false);
 async function loadClosures(){const next=await closureService.load();setClosures(next);setClosuresReady(true);}
 const closureSync=useSync('closures',loadClosures);
 const [tags,setTags]=useState<TagsConfig|null>(null);
 async function loadTags(){setTags(await tagsService.load());}
 const tagsSync=useSync('id-tags',loadTags);
 const item=draft.current,context={draft,designs,fonts,closures,closuresReady,tags,tagsReady:!!tags,catalogReady:catalogState==='ready'},currentStep=getCurrentStep(context),step=currentStep.id,progress=getProgress(context);
 const eyebrow=step==='customer-name'?null:['customer-phone','size','design','fastening','tag-type','tag-shape'].includes(step)?null:step==='width'?`${locale==='es'?'TU TALLA SELECCIONADA':'YOUR SELECTED SIZE'} · ${item.size_code}`:step==='pet-name'?(locale==='es'?'PARA LA PLACA DE IDENTIFICACIÓN':'FOR THE ID TAG'):null;
 const selectedUnavailable=catalogState==='ready'&&[...(step==='order-summary'?draft.items:[]),item].some(i=>i.design_id&&!designs.some(d=>d.id===i.design_id&&compatible(d,i.size_code,i.width_cm)));
 const previousStep=useRef(step);
 useEffect(()=>{if(stepIds.indexOf(step)>stepIds.indexOf(previousStep.current)&&(currentStep.progressKey||step)!==(stepsConfig.find(s=>s.id===previousStep.current)?.progressKey||previousStep.current))onAdvance?.();previousStep.current=step;},[step,onAdvance]);
 async function recoverConfirmation(){setRecovering(true);setError('');try{const saved=await confirmation.resume();if(saved){setOrder(saved);setConfirmationPending(false);setConfirmationConflict(false);sessionStorage.removeItem(DRAFT_KEY);}}catch(e){setError(errorMessage(e,locale,'recovery'));}finally{setRecovering(false);}}
 useEffect(()=>{if(getConfirmationCheckpoint())recoverConfirmation();},[]);
 async function catalog(){if(!designs.length)setCatalogState('loading');try{const c=await loadCatalog();setDesigns(c.designs);setFonts(c.fonts);setCatalogState('ready');}catch{if(!designs.length)setCatalogState('error');throw Error('CATALOG_SYNC_FAILED');}}
 useSync('catalog',catalog);
 useEffect(()=>{if(order||recovering)return;try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify(draft));}catch{/* memory draft still usable */}},[draft,order,recovering]);
 useEffect(()=>{setError('');setNotice('');heading.current?.focus({preventScroll:true});const area=heading.current?.closest('.configurator-area');if(area)area.scrollTop=0;window.scrollTo({top:0,behavior:'instant'});if(['customer-name','customer-phone','pet-name','tag-phone'].includes(step))input.current?.focus();},[step]);
 useEffect(()=>{if(item.design_id){const d=designs.find(d=>d.id===item.design_id);if(d)setTab(d.type);}},[step]);
 useEffect(()=>{
  if(busy)return;
  if(item.personalization_type!==retryPurpose.current||(uploadState==='ready'&&!item.attachments.some(a=>a.purpose===retryPurpose.current))){
   setUploadState('');setUploadError('');retryFile.current=null;retryPurpose.current=itemPurposeDefault;
  }
 },[item.id,item.personalization_type,item.attachments,busy,uploadState]);
 function update(patch:Partial<typeof item>){setDraft(d=>({...d,current:{...d.current,...patch}}));setError('');}
 function change(code:string){const next=changeSize(item,code,designs);if(item.design_id&&!next.design_id)setNotice(t('changed'));setDraft(d=>({...d,current:next}));}
 function next(){if(!canContinue(context)){setError(step==='customer-phone'||step==='tag-phone'?t('invalidPhone'):t('required'));return;}const nextStep=getNextStep(context);setDraft(d=>({...d,current:step==='customer-phone'?{...d.current,tag_phone:d.current.tag_phone||d.customer.phone}:d.current,step:nextStep}));}
 function back(){setDraft(d=>({...d,step:getPreviousStep(context)}));}
 async function send(){if(lock.current||unrecoveredConfirmation){setError(locale==='es'?'Recupera primero el pedido confirmado antes de guardar otro.':'Recover the confirmed order before saving another one.');return;}setError('');if(!confirmationPending&&!canContinue(context)){const invalid=draft.items.find(i=>validateCollar(i,designs,fonts,tags).length||!validClosure(i,closures)||!tags||!validConfiguredTag(tags,i));if(invalid){setDraft(d=>editItem(d,invalid));setError(t('check'));}else setError(t('required'));return;}lock.current=true;setBusy(true);try{
  // A lost confirmation response is recovered using the same durable key.
  setConfirmationPending(true);const confirmed=await confirmation.submit(draft);confirmedAt.current=Date.now();setOrder(confirmed);setConfirmationPending(false);sessionStorage.removeItem(DRAFT_KEY);
 }catch(e){const failure=normalizeError(e,'confirmation');if(failure.kind==='conflict')setConfirmationConflict(true);if(failure.kind==='validation'&&failure.reason){clearConfirmationCheckpoint();setConfirmationPending(false);await Promise.all([catalog(),loadClosures()]);}setError(errorMessage(e,locale,'confirmation'));}finally{lock.current=false;setBusy(false);}}
 async function addFile(file:File,purpose=item.personalization_type){if(lock.current||item.attachments.some(a=>a.purpose===purpose))return;lock.current=true;setBusy(true);setUploadState('uploading');setUploadError('');setError('');retryFile.current=file;retryPurpose.current=purpose;try{const current=selectPersonalization(item,purpose);update({...current,attachments:[]});const a=await upload(file,{...draft,current},setUploadState);update({...current,attachments:[a]});retryFile.current=null;setUploadState('ready');}catch(e){setUploadState('error');setUploadError(errorMessage(e,locale,'upload'));}finally{lock.current=false;setBusy(false);if(fileInput.current)fileInput.current.value='';}}
 const options=(values:string[],selected:string,fn:(v:string)=>void)=><OptionGrid>{values.map(v=><IconOption key={v} selected={v===selected} onSelect={()=>fn(v)} label={t(v as TextKey)} className="option id-tag-option" icon={<img className="id-tag-icon" src={import.meta.env.BASE_URL+'icons/id-tag-'+(v==='hanging'?'hanging':'anti-fall')+'.svg'} alt="" aria-hidden="true"/>}/>)}</OptionGrid>;
 const previewItem=(value:Item)=>{const i=tags?{...value,tag_snapshot:tagSnapshot(tags,value)}:value;const c=closures.find(c=>c.key===i.collar_type);return c?{...i,closure_snapshot:{key:c.key,name_en:c.name_en,name_es:c.name_es,icon:c.icon}}:i;};
 const field=(value:string,fn:(v:string)=>void,kind='text',placeholder='')=><input ref={input} aria-label={t(currentStep.title)} className="big-input" type={kind} value={value} placeholder={placeholder} maxLength={kind==='tel'?32:200} autoComplete={step==='customer-name'?'name':step==='customer-phone'?'tel':'off'} onChange={e=>fn(e.target.value)} aria-invalid={!!error} aria-describedby={error?'step-error':undefined}/>;
 if(recovering)return <section className="flow"><p role="status">{t('loading')}</p></section>;
 if(order)return <section className="flow complete"><OrderDetail order={order} locale={locale}/><button className="confirmation-restart" onClick={()=>{if(Date.now()-confirmedAt.current<700)return;clearConfirmationCheckpoint();setConfirmationPending(false);setOrder(null);setDraft(blankDraft());}}>{t('restart')}</button><ConfirmationDate order={order} locale={locale}/></section>;
 return <section data-flow-step={step} className={step==='order-summary'?'flow order-summary-flow':step==='tag-shape'?'flow tag-shape-flow':step==='design'?'flow design-flow':'flow'}>{unrecoveredConfirmation&&<div role="alert" className="error recovery-notice"><p>{error||errorMessage(null,locale,'recovery')}</p><button type="button" className="primary" onClick={recoverConfirmation} disabled={recovering}>{recovering?t('loading'):t('retry')}</button><small>{locale==='es'?'El pedido se mantiene protegido. Recupéralo antes de confirmar otro.':'Your order remains protected. Recover it before confirming another order.'}</small></div>}<ProgressBar label={progress.group==='customer'?(locale==='es'?'HECHO PARA TU MEJOR AMIGO':'MADE FOR YOUR BEST FRIEND'):step==='order-summary'?(locale==='es'?'TU ORDEN':'YOUR ORDER'):`${t('draft')}${locale==='es'?' ·':''} ${draft.items.findIndex(i=>i.id===item.id)>=0?draft.items.findIndex(i=>i.id===item.id)+1:draft.items.length+1}`} counter={step==='order-summary'?String(draft.items.length):`${progress.current} / ${progress.total}`} percent={progress.percent}/><form onSubmit={e=>{e.preventDefault();if(!busy&&!['review','order-summary'].includes(step))next();}}>
 <div className="flow-question">{step!=='order-summary'&&<StepHeader ref={heading} eyebrow={eyebrow} title={step==='tag-shape'?(locale==='es'?'Elige la forma de la placa.':'Choose the tag shape.'):step==='tag-details'?(locale==='es'?'¿Añadir algún detalle extra?':'Add any extra details?'):t(currentStep.title)}>{step==='tag-details'&&<p className="muted">{locale==='es'?'Opcional — elige solo lo que quieras incluir.':"Optional — choose only what you'd like to include."}</p>}{step==='personalization'&&<p className="muted">{t('optional')}</p>}</StepHeader>}
 
 <div key={step} className="flow-content">
 {step==='customer-name'&&field(draft.customer.name,v=>setDraft(d=>({...d,customer:{...d.customer,name:v},key:uuid()})),'text',t('nameHint'))}
 {step==='customer-phone'&&field(draft.customer.phone,v=>setDraft(d=>({...d,customer:{...d.customer,phone:v},key:uuid()})),'tel',t('phoneHint'))}
 {step==='size'&&<><div className="size-grid">{sizes.map(s=><button type="button" aria-pressed={item.size_code===s.code} className={`size-option ${item.size_code===s.code?'selected':''}`} key={s.code} onClick={()=>change(s.code)}><strong>{s.code}</strong><small>{s.min}–{s.max} cm</small></button>)}</div><button type="button" className="text-button size-guide-link" onClick={()=>setGuide(true)}>{t('sizeHelp')}</button></>}
 {step==='width'&&<><div className="options">{getAvailableWidths(item.size_code).map(w=><button type="button" aria-pressed={item.width_cm===w} className={`option ${item.width_cm===w?'selected':''}`} key={w} onClick={()=>{const valid=designs.some(d=>d.id===item.design_id&&compatible(d,item.size_code,w));if(item.design_id&&!valid)setNotice(t('changed'));update({width_cm:w,design_id:valid?item.design_id:''});}}><span>{w.toFixed(1)} cm</span></button>)}</div>{getAvailableWidths(item.size_code).length===1&&<p className="muted">{t('oneWidth')}</p>}</>}
 {step==='design'&&<><div className="tabs" role="tablist" aria-label={locale==='es'?'Colecciones':'Collections'}>{(['woven','printed'] as const).map(v=><button type="button" role="tab" id={`collection-${v}`} aria-controls="catalog-panel" aria-selected={tab===v} tabIndex={tab===v?0:-1} key={v} onClick={()=>setTab(v)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'woven':e.key==='End'?'printed':v==='woven'?'printed':'woven';setTab(next);document.getElementById('collection-'+next)?.focus();}}}>{t(v)}</button>)}</div><section id="catalog-panel" role="tabpanel" aria-labelledby={`collection-${tab}`}>{catalogState==='loading'?<p role="status">{t('loading')}</p>:catalogState==='error'?<div role="alert"><p>{errorMessage(null,locale,'catalog')}</p><button type="button" onClick={()=>void catalog().catch(()=>{})}>{t('retry')}</button></div>:<DesignGallery designs={getAvailableDesigns(designs,item.size_code,item.width_cm,tab)} family={tab} locale={locale} selected={item.design_id} onSelect={id=>update({design_id:id})} onPreview={setZoom}/>}</section></>}
 {step==='fastening'&&closuresReady&&!validClosure(item,closures)&&<button className="option selected" aria-pressed="true" disabled>{closures.find(c=>c.key===item.collar_type)?closureName(closures.find(c=>c.key===item.collar_type)!,locale):item.collar_type} · {locale==='es'?'No disponible':'Unavailable'}</button>}
 {step==='fastening'&&<>{!closuresReady?closureSync==='issue'?<p role="alert" className="error">{locale==='es'?'No pudimos cargar los cierres.':'We couldn’t load closures.'}<button type="button" onClick={()=>void loadClosures().catch(()=>{})}>{t('retry')}</button></p>:<p role="status">{t('loading')}</p>:<OptionGrid>{availableClosures(closures,item.size_code,item.width_cm).map(c=><IconOption key={c.key} selected={c.key===item.collar_type} onSelect={()=>update({collar_type:c.key})} label={closureName(c,locale)} className="option closure-option" icon={<ProductIcon className={'closure-icon closure-icon-'+c.key} path={c.icon}/>}/>)}</OptionGrid>}</>}
 {closuresReady&&['fastening','review','order-summary'].includes(step)&&!(step==='order-summary'?draft.items.every(i=>validClosure(i,closures)):validClosure(item,closures))&&<p className="error" role="alert">{locale==='es'?'El cierre seleccionado ya no está disponible para esta talla y ancho. Elige otro cierre.':'The selected closure is unavailable for this size and width. Choose another closure.'}{step!=='fastening'&&<button type="button" className="text-button" onClick={()=>{const invalid=step==='order-summary'?draft.items.find(i=>!validClosure(i,closures)):item;if(invalid)setDraft(d=>({...editItem(d,invalid),step:'fastening'}));}}>{locale==='es'?'Cambiar cierre':'Change closure'}</button>}</p>}
 {step==='tag-type'&&tags&&!tagTypeAvailable(tags,item.tag_type,item)&&<button className="option selected" aria-pressed="true" disabled>{tags.types.find(v=>v.key===item.tag_type)?.[locale==='es'?'name_es':'name_en']} · {locale==='es'?'No disponible':'Unavailable'}</button>}
 {step==='tag-type'&&tags&&<OptionGrid>{sorted(tags.types).filter(v=>tagTypeAvailable(tags,v.key as Item['tag_type'],item)).map(v=><IconOption key={v.key} selected={item.tag_type===v.key} onSelect={()=>update({tag_type:v.key as Item['tag_type'],...(v.key==='anti_fall'?{tagShape:undefined,tagSize:undefined,tagWidthCm:undefined,tagHeightCm:undefined}:{})})} label={locale==='es'?v.name_es:v.name_en} className="option id-tag-option" icon={<ProductIcon className={'id-tag-icon id-tag-icon-'+v.key} path={v.icon}/>}/>)}</OptionGrid>}
 {['tag-type','tag-shape','review','order-summary'].includes(step)&&(!tags||!(step==='order-summary'?draft.items.every(i=>validConfiguredTag(tags,i)):tagTypeAvailable(tags,item.tag_type,item)&&(step==='tag-type'||step==='tag-shape'&&(!item.tagShape||tagAwaitingSize(tags,item))||validConfiguredTag(tags,item))))&&<p role="alert" className="error">{!tags?tagsSync==='issue'?'Could not load ID Tags.':'Loading ID Tags…':locale==='es'?'La placa seleccionada ya no está disponible. Elige otra opción.':'The selected ID tag is unavailable. Choose another option.'}<button type="button" onClick={()=>{if(!tags)void loadTags().catch(()=>{});else {const invalid=step==='order-summary'?draft.items.find(i=>!validConfiguredTag(tags,i)):item;if(invalid)setDraft(d=>({...editItem(d,invalid),step:'tag-type'}));}}}>{!tags?t('retry'):locale==='es'?'Cambiar placa':'Change ID tag'}</button></p>}
 {step==='tag-shape'&&tags&&item.tagShape&&!sorted(tags.hanging).some(m=>m.key===item.tagShape)&&<button className="option selected" aria-pressed="true" disabled>{tags.hanging.find(m=>m.key===item.tagShape)?.[locale==='es'?'name_es':'name_en']} · {locale==='es'?'No disponible':'Unavailable'}</button>}
 {step==='tag-shape'&&<div className="tag-shape-grid">{(tags?sorted(tags.hanging).filter(m=>m.sizes.some(s=>s.active)):[]).map(m=><button type="button" className={`tag-shape-option ${item.tagShape===m.key?'selected':''}`} aria-pressed={item.tagShape===m.key} key={m.key} onClick={()=>{if(tags)update(selectConfiguredShape(tags,item,m.key as typeof item.tagShape & string));}}><ProductIcon className="tag-shape-icon" path={m.icon}/><span>{locale==='es'?m.name_es:m.name_en}</span></button>)}</div>}
 {step==='tag-shape'&&!item.tagShape&&<div className="tag-size-space" aria-hidden="true"/>}
 {step==='tag-shape'&&tags&&item.tagSize&&!tags.hanging.find(m=>m.key===item.tagShape)?.sizes.some(s=>s.id===item.tagSize&&s.active)&&<button className="option selected" aria-pressed="true" disabled>{tags.hanging.find(m=>m.key===item.tagShape)?.sizes.find(s=>s.id===item.tagSize)?.[locale==='es'?'name_es':'name_en']||item.tagSize} · {locale==='es'?'No disponible':'Unavailable'}</button>}
 {step==='tag-shape'&&item.tagShape&&<section key={item.tagShape} className="tag-inline-sizes" aria-labelledby="tag-size-heading"><h2 id="tag-size-heading">{locale==='es'?'Elige un tamaño.':'Choose a size.'}</h2><div className="tag-size-grid">{(tags?.hanging.find(m=>m.key===item.tagShape)?.sizes.filter(s=>s.active)||[]).map(s=><button type="button" className={`option tag-size-option ${item.tagSize===s.id?'selected':''}`} aria-pressed={item.tagSize===s.id} key={s.id} onClick={()=>update({tagSize:s.id,tagWidthCm:s.width,tagHeightCm:s.height})}><strong>{locale==='es'?s.name_es:s.name_en}</strong><small>{s.width} × {s.height} cm</small></button>)}</div></section>}
 {step==='pet-name'&&field(item.pet_name,v=>update({pet_name:v}),'text',t('petHint'))}
 {step==='tag-phone'&&<>{field(item.tag_phone,v=>update({tag_phone:v}),'tel',t('phoneHint'))}<button type="button" className="text-button" onClick={()=>update({tag_phone:draft.customer.phone})}>{t('usephone')}</button></>}
 {step==='tag-details'&&<TagExtraDetails item={item} locale={locale} onChange={update}/>}
 {catalogState==='ready'&&['lettering','personalization','review','order-summary'].includes(step)&&!(step==='order-summary'?draft.items.every(i=>fonts.some(f=>f.number===i.font_number&&f.active)):fonts.some(f=>f.number===item.font_number&&f.active))&&<p className="error" role="alert">{locale==='es'?'El estilo de letra seleccionado ya no está disponible. Elige otro estilo.':'The selected lettering style is no longer available. Choose another style.'}{step!=='lettering'&&<button type="button" className="text-button" onClick={()=>{const invalid=step==='order-summary'?draft.items.find(i=>!fonts.some(f=>f.number===i.font_number&&f.active)):item;if(invalid)setDraft(d=>({...editItem(d,invalid),step:'lettering'}));}}>{locale==='es'?'Cambiar estilo':'Change lettering style'}</button>}</p>}
 {step==='lettering'&&<>{catalogState!=='ready'?<><p>{t(catalogState==='loading'?'loading':'error')}</p><button type="button" onClick={catalog}>{t('retry')}</button></>:<LetteringSelector fonts={fonts} number={item.font_number} name={item.pet_name} locale={locale} onConfirm={font_number=>update({font_number})}/>}</>}
 
 {step==='personalization'&&<PersonalityOptions font={fonts.find(f=>f.number===item.font_number)} item={item} locale={locale} busy={busy} onChange={update}>{purpose=>{const hasAttachment=item.attachments.some(a=>a.purpose===purpose),statusVisible=!!uploadState&&retryPurpose.current===purpose;return <div className="engraving-upload-control">{!hasAttachment&&<label className={`upload-box ${hasAttachment?'has-upload':''}`}><span className="upload-icon" aria-hidden="true">↑</span><strong>{hasAttachment?(locale==='es'?'Añadir otra imagen':'Add another image'):t('selectFile')}</strong><small>{t('fileLimit')}</small><input aria-label={`${t('selectFile')} — ${t(purpose)}`} aria-invalid={uploadState==='error'&&retryPurpose.current===purpose} aria-describedby={uploadState==='error'&&retryPurpose.current===purpose?'upload-error-'+purpose:undefined} type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" disabled={busy||item.attachments.length>=1} onChange={e=>{const file=e.target.files?.[0];if(file)addFile(file,purpose);e.currentTarget.value='';}}/></label>}<Reveal open={statusVisible||hasAttachment}>{statusVisible&&uploadState!=='ready'&&<p id={'upload-error-'+purpose} role={uploadState==='error'?'alert':'status'}>{uploadState==='error'?uploadError:t('uploading')}</p>}{statusVisible&&uploadState==='error'&&retryFile.current&&<button type="button" disabled={busy} onClick={()=>{if(retryFile.current)addFile(retryFile.current,purpose);}}>{t('retry')}</button>}{item.attachments.filter(a=>a.purpose===purpose).map(a=><div key={a.id} className="file-row"><AttachmentThumbnail attachment={a} locale={locale}/><span className="uploaded-file-info">{uploadState!=='error'&&<small>{locale==='es'?'✓ Imagen cargada':'✓ Image uploaded'}</small>}<span>{a.original_filename}</span></span><button type="button" disabled={busy} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setUploadError('');setUploadState('');retryFile.current=null;retryPurpose.current=purpose;setError('');try{await discard(a);update({attachments:[]});setUploadState('');setUploadError('');retryPurpose.current=itemPurposeDefault;if(fileInput.current)fileInput.current.value='';}catch(e){retryPurpose.current=purpose;setUploadState('error');setUploadError(errorMessage(e,locale,'upload'));}finally{lock.current=false;setBusy(false);}}}>{t('remove')}</button></div>)}</Reveal></div>}}</PersonalityOptions>}
 {step==='review'&&<><CollarReview item={previewItem(item)} design={designs.find(d=>d.id===item.design_id)} font={fonts.find(f=>f.number===item.font_number)} locale={locale} onEdit={s=>setDraft(d=>({...d,step:s}))}/></>}
 {step==='order-summary'&&<><div className="customer-strip"><span>{draft.customer.name}<small>{draft.customer.phone}</small></span><button type="button" disabled={busy||confirmationPending} onClick={()=>setDraft(d=>({...d,step:'customer-name'}))}>{t('editCustomer')}</button></div>{draft.items.map((i,n)=><CollapsibleCollar key={i.id} item={previewItem(i)} number={n+1} design={designs.find(d=>d.id===i.design_id)} font={fonts.find(f=>f.number===i.font_number)} locale={locale} actions={<div className="order-collar-actions"><button type="button" className="text-button" aria-label={`${t('edit')}: collar ${n+1}`} disabled={busy||confirmationPending} onClick={()=>setDraft(d=>editItem(d,i))}>{t('edit')}</button><button type="button" className="text-button order-collar-remove" aria-label={`${t('remove')}: collar ${n+1}`} disabled={busy||confirmationPending} onClick={()=>setDraft(d=>removeItem(d,i.id))}>{t('remove')}</button></div>}><div className="order-expanded-review"><CollarReview showName={false} item={previewItem(i)} design={designs.find(d=>d.id===i.design_id)} font={fonts.find(f=>f.number===i.font_number)} locale={locale}/></div></CollapsibleCollar>)}<button type="button" className="add-collar wide" disabled={busy||confirmationPending||draft.items.length>=20} onClick={()=>setDraft(addItem)}>＋ {t('add')}</button><p className="muted">{t('confirmation')}</p></>}
 {selectedUnavailable&&<p role="alert" className="error">{locale==='es'?'El diseño seleccionado ya no está disponible para esta talla y ancho. Elige otro antes de realizar el pedido.':'The selected design is unavailable for this size and width. Choose another before saving your order.'}</p>}<Reveal open={!!notice}><p role="status" className="notice">{notice}</p></Reveal><Reveal open={!!error}><p id="step-error" role="alert" className="error">{error}</p></Reveal>
 </div>
 </div>
 {step==='review'&&<div className="flow-actions"><button type="button" className="text-button" disabled={busy} onClick={back}>← {t('back')}</button><div className="button-row"><button type="button" className="primary" disabled={busy||catalogState!=='ready'||!canContinue(context)} onClick={()=>{if(!canContinue(context)){setError(t('check'));return;}setDraft(saveItem);}}>{t('save')} →</button></div></div>}
 {step==='order-summary'&&<div className="flow-actions"><button type="button" className="primary" disabled={unrecoveredConfirmation||busy||draft.items.length===0||mode==='unconfigured'||(!confirmationPending&&!canContinue(context))} onClick={confirmationConflict?recoverConfirmation:send}>{busy?t('recording'):confirmationPending?t('retry'):mode==='demo'?t('demoConfirm'):t('confirm')}{confirmationPending&&!busy?' →':''}</button></div>}
 {!['review','order-summary'].includes(step)&&<NavigationActions backLabel={t('back')} nextLabel={busy?t('pending'):t('next')} skipLabel={step==='tag-details'&&extraEntries(item,locale).length===0?t('skip'):undefined} onBack={back} onSkip={next} backDisabled={step==='customer-name'||busy} nextDisabled={busy||isContinueDisabled(context)}/>}

 </form>
 {zoom&&<DesignPreview design={zoom} locale={locale} size={item.size_code} width={item.width_cm} onClose={()=>setZoom(null)} onSelect={()=>{update({design_id:zoom.id});setZoom(null);}}/>}
 {guide&&<Modal label={t('sizeHelp')} onClose={()=>setGuide(false)}><button className="modal-close" onClick={()=>setGuide(false)}>{t('close')} ×</button><h2>{t('sizeHelp')}</h2><div className="table-scroll"><table><thead><tr><th>{locale==='es'?'Talla':'Size'}</th><th>cm</th><th>{locale==='es'?'Ancho cm':'Width cm'}</th><th>kg</th></tr></thead><tbody>{sizes.map(s=><tr key={s.code}><th>{s.code}</th><td>{s.min}–{s.max}</td><td>{s.widths.map(w=>w.toFixed(1)).join(' / ')}</td><td>{s.weight}</td></tr>)}</tbody></table></div></Modal>}
 </section>;
}


















