import {errorMessage} from '../application/errors';
import {useEffect,useState} from 'react';
import {advance,checkOwner,listOrders,mode,readDemo,signIn,signOut,subscribeAuth,getProductionOrder,clearConfirmationCheckpoint} from '../data/backend';
import {OrderDetail} from '../components';
import {translator} from '../i18n';
import {DRAFT_KEY} from '../configurator/state';
import type {Locale,Order,Status} from '../domain/model';
export default function Production({locale}:{locale:Locale}){
 const t=translator(locale);const [owner,setOwner]=useState(false),[checking,setChecking]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[orders,setOrders]=useState<Order[]>([]),[selected,setSelected]=useState<Order|null>(null),[status,setStatus]=useState<Status|''>(''),[page,setPage]=useState(0);
 async function authorize(){setChecking(true);try{setOwner(await checkOwner());}catch(e){setError(errorMessage(e,locale,'production'));}finally{setChecking(false);}}
 useEffect(()=>{authorize();return subscribeAuth(authorize);},[]);
 async function refresh(){setBusy(true);setError('');try{setOrders(await listOrders(status,page));}catch(e){setError(errorMessage(e,locale,'production'));}finally{setBusy(false);}}
 useEffect(()=>{if(owner)refresh();},[owner,status,page]);
 if(mode!=='live')return <section className="panel"><p className="eyebrow">{t('production')}</p><h1>{t('login')}</h1><p className="notice">{t('noBackend')}</p><p>{t('demo')}</p>{readDemo().map(o=><details key={o.id}><summary>{o.order_code} · {o.customer_snapshot.name}</summary><OrderDetail order={o} locale={locale} production/></details>)}</section>;
 if(checking)return <p role="status">{t('loading')}</p>;
 if(!owner)return <section className="panel login"><p className="eyebrow">COLTI / {t('production')}</p><h1>{t('login')}</h1><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await signIn(email,password);if(!await checkOwner()){await signOut();setError(t('unauthorized'));}else setOwner(true);}catch(e){setError(errorMessage(e,locale,'login'));}finally{setBusy(false);setPassword('');}}}><label>{t('email')}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>{t('password')}<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={busy}>{busy?t('pending'):t('login')}</button></form>{error&&<p role="alert" className="error">{error}</p>}</section>;
 return <section className="panel production"><div className="panel-top"><p className="eyebrow">COLTI / {t('production')}</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await signOut();sessionStorage.removeItem(DRAFT_KEY);clearConfirmationCheckpoint();setOwner(false);setOrders([]);setSelected(null);}catch(e){setError(errorMessage(e,locale,'login'));}finally{setBusy(false);}}}>{t('logout')}</button></div>{error&&<p role="alert" className="error">{error}<button disabled={busy} onClick={refresh}>{t('retry')}</button></p>}{selected?<><button className="text-button" onClick={()=>setSelected(null)}>← {t('back')}</button><OrderDetail order={selected} locale={locale} production/>{selected.status!=='finished'&&<button className="primary" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);setError('');try{const o=await advance(selected);setSelected(o);setOrders(v=>v.map(x=>x.id===o.id?o:x));}catch(e){setError(errorMessage(e,locale,'production'));try{const current=await getProductionOrder(selected.id);if(current)setSelected(current);}catch{/* leave the current order available for retry */}}finally{setBusy(false);}}}>{busy?t('pending'):`${t('advance')} ${t(selected.status==='new'?'in_progress':'finished')}`}</button>}</>:<><h1>{t('all')}</h1><label>{t('all')}<select value={status} onChange={e=>{setStatus(e.target.value as Status|'');setPage(0);}}><option value="">{t('all')}</option>{(['new','in_progress','finished'] as const).map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label>{busy?<p role="status">{t('loading')}</p>:orders.length?orders.map(o=><button className="order-list-row" key={o.id} onClick={()=>setSelected(o)}><strong>{o.order_code}</strong><span>{o.customer_snapshot.name}</span><span>{o.items.length} · {t(o.status)}</span><time>{new Date(o.confirmed_at).toLocaleDateString(locale)}</time></button>):<p>{t('noOrders')}</p>}<div className="button-row"><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>{t('previous')}</button><span>{page+1}</span><button disabled={orders.length<20||busy} onClick={()=>setPage(p=>p+1)}>{t('nextPage')}</button></div></>}</section>;
}

