import {describe,it,expect} from 'vitest';
import fixtures from '../data/closure-fixtures.json';
import {availableClosures,closureAvailable,setClosureSize,setClosureWidth,validateClosure,widthEnabled,type Closure} from './closures';
import {blankDraft,sizes} from './model';
import {canContinue,isContinueDisabled} from '../configurator/steps';
import {closureApplication} from '../application/closures';
import {getCollarSummary} from './presentation';
const seed=()=>structuredClone(fixtures[0]) as Closure;
describe('closure availability',()=>{
 it('consumes every master pair and rejects invalid pairs',()=>{const c=seed();for(const s of sizes)for(const w of s.widths)expect(closureAvailable(c,s.code,w)).toBe(true);expect(closureAvailable(c,'M',3)).toBe(false);expect(()=>setClosureWidth(c,'M',3,false)).toThrow();expect(()=>setClosureSize(c,'fake',true)).toThrow();});
 it('single width is implicit; multi-width preferences independently gate',()=>{let c=seed();c.preferences.M={enabled:true,widths:{'2.5':false}};expect(widthEnabled(c,'M',2.5)).toBe(true);c=setClosureWidth(c,'XS',1,false);expect(closureAvailable(c,'XS',1)).toBe(false);expect(closureAvailable(c,'XS',1.5)).toBe(true);expect(()=>setClosureWidth(c,'M',2.5,false)).toThrow();});
 it('size OFF and closure OFF retain all width preferences',()=>{let c=setClosureWidth(seed(),'ML',2.5,false);const preferences=structuredClone(c.preferences);c=setClosureSize(c,'ML',false);expect(closureAvailable(c,'ML',3)).toBe(false);expect(c.preferences.ML.widths).toEqual(preferences.ML.widths);c=setClosureSize(c,'ML',true);expect(closureAvailable(c,'ML',2.5)).toBe(false);expect(closureAvailable(c,'ML',3)).toBe(true);expect(availableClosures([{...c,active:false}],'ML',3)).toEqual([]);expect({...c,active:false}.preferences).toEqual(c.preferences);});
 it('sorts configured options, validates names and uploaded icon paths',()=>{const c=validateClosure({...seed(),name_en:'Buckle',name_es:'Hebilla',icon:'closures/uploads/12345678-1234-1234-1234-123456789abc-320.webp',display_order:2});expect(c.name_es).toBe('Hebilla');expect(availableClosures([c,{...seed(),key:'martingale',display_order:0}],'S',2).map(v=>v.key)).toEqual(['martingale','plastic_buckle']);expect(()=>validateClosure({...c,icon:'javascript:alert(1)'})).toThrow();expect(()=>validateClosure({...c,name_en:''})).toThrow();});
 it('does not erase a selected option when invalidated, and blocks navigation',()=>{const draft=blankDraft();draft.step='fastening';draft.current.size_code='S';draft.current.width_cm=2;const context={draft,designs:[],fonts:[],catalogReady:true,closuresReady:true,closures:[seed()]};expect(canContinue(context)).toBe(true);expect(canContinue({...context,closures:[{...seed(),active:false}]})).toBe(false);expect(isContinueDisabled({...context,closures:[{...seed(),active:false}]})).toBe(true);expect(draft.current.collar_type).toBe('plastic_buckle');});
 it('application validates before writes and uses repository reads for fallback',async()=>{let reads=0,writes=0;const app=closureApplication({create:async c=>({...c,revision:1}),load:async()=>{reads++;return [seed()];},save:async c=>{writes++;return {...c,revision:c.revision+1};},uploadIcon:async()=>'/icons/martingale.svg'});await app.load();await app.load();expect(reads).toBe(2);expect((await app.save(seed())).revision).toBe(2);expect(()=>app.save({...seed(),preferences:{M:{enabled:true,widths:{'3':true}}}})).toThrow();expect(writes).toBe(1);});
 it('historical names are taken from snapshots instead of current settings',()=>{const item={...blankDraft().current,closure_snapshot:{key:'plastic_buckle' as const,name_en:'Original buckle',name_es:'Hebilla original',icon:'/icons/plastic-buckle.svg'}};expect(getCollarSummary(item,'en').fastening).toBe('Original buckle');expect(getCollarSummary(item,'es').fastening).toBe('Hebilla original');});
});
