import {validPair,type Item,type TagType} from './model';
import {tagModels,type TagShape} from './tags';
export interface TagCommon {deleted?:boolean;key:string;name_en:string;name_es:string;icon:string;active:boolean;display_order:number}
export interface HangingSize {id:string;name_en:string;name_es:string;width:number;height:number;active:boolean}
export interface HangingModel extends TagCommon {sizes:HangingSize[]}
export const antiRibbonWidths:Record<string,number>={micro:1,miniature:1,small:1.5,semi_medium:2,medium:2.5,large:3};
export interface AntiModel extends TagCommon {width:number;height:number}
export interface TagsConfig {revision:number;types:TagCommon[];hanging:HangingModel[];anti:AntiModel[];mapping:{size:string;width:number;model:string}[]}
const common=(key:string,en:string,es:string,icon:string,order:number)=>({key,name_en:en,name_es:es,icon,active:true,display_order:order});
export const initialTags:TagsConfig={revision:1,types:[common('hanging','Hanging','Colgante','/icons/id-tag-hanging.svg',0),common('anti_fall','Anti-fall','Anticaída','/icons/id-tag-anti-fall.svg',1)],hanging:tagModels.map((m,n)=>({...common(m.shape,m.en,m.es,m.shape==='crown'?'/icons/id-tag-hanging.svg':'/icons/tag-'+m.shape+'.svg',n),active:!('active' in m&&m.active===false),sizes:m.sizes.map(s=>({id:s.id,name_en:s.en,name_es:s.es,width:s.width,height:s.height,active:true}))})),anti:[['micro','Micro','Micro',3,1.2],['miniature','Miniature','Miniatura',4,1.5],['small','Small','Pequeña',3.5,2],['semi_medium','Semi Medium','Semimediana',4.3,2.2],['medium','Medium','Mediana',5,3],['large','Large','Grande',6,4]].map(([k,en,es,w,h],n)=>({...common(String(k),String(en),String(es),'/icons/id-tag-anti-fall.svg',n),width:Number(w),height:Number(h)})),mapping:[['2XS',1,'micro'],['XS',1,'miniature'],['XS',1.5,'small'],['S',1.5,'small'],['S',2,'semi_medium'],['SM',2,'semi_medium'],['M',2.5,'medium'],['ML',2.5,'medium'],['ML',3,'large'],['L',3,'large'],['XL',3,'large'],['2XL',3,'large']].map(([s,w,m])=>({size:String(s),width:Number(w),model:String(m)}))};
export const sorted=<T extends TagCommon>(values:T[])=>values.filter(v=>v.active&&!v.deleted).sort((a,b)=>a.display_order-b.display_order);
export function resolveAnti(c:TagsConfig,i:Pick<Item,'size_code'|'width_cm'>){if(!validPair(i.size_code,i.width_cm))return;const map=c.mapping.find(m=>m.size===i.size_code&&m.width===i.width_cm);return c.anti.find(m=>m.key===map?.model&&m.active&&!m.deleted);}
export function tagTypeAvailable(c:TagsConfig,key:TagType,i:Item){return validPair(i.size_code,i.width_cm)&&!!c.types.find(t=>t.key===key&&t.active)&&(key==='anti_fall'?!!resolveAnti(c,i):c.hanging.some(m=>m.active&&!m.deleted&&m.sizes.some(s=>s.active)));}
export function validConfiguredTag(c:TagsConfig,i:Item){if(!tagTypeAvailable(c,i.tag_type,i))return false;if(i.tag_type==='anti_fall')return true;return c.hanging.some(m=>m.key===i.tagShape&&m.active&&!m.deleted&&!m.deleted&&m.sizes.some(s=>s.active&&s.id===i.tagSize&&s.width===i.tagWidthCm&&s.height===i.tagHeightCm));}
export function selectConfiguredShape(c:TagsConfig,i:Item,shape:TagShape):Item{const sizes=c.hanging.find(m=>m.key===shape)?.sizes.filter(s=>s.active)||[];const s=sizes.length===1?sizes[0]:shape===i.tagShape?sizes.find(s=>s.id===i.tagSize):undefined;return {...i,tagShape:shape,tagSize:s?.id,tagWidthCm:s?.width,tagHeightCm:s?.height};}
export interface TagSnapshot {type:TagCommon;model:TagCommon;size?:HangingSize;width:number;height:number}
export function tagSnapshot(c:TagsConfig,i:Item):TagSnapshot|undefined {const type=c.types.find(t=>t.key===i.tag_type);const model=i.tag_type==='anti_fall'?resolveAnti(c,i):c.hanging.find(m=>m.key===i.tagShape);if(!type||!model)return;const size=i.tag_type==='hanging'?(model as HangingModel).sizes.find(s=>s.id===i.tagSize):undefined;return {type,model,size,width:size?.width||(model as AntiModel).width,height:size?.height||(model as AntiModel).height};}
export function validateTags(c:TagsConfig):TagsConfig{if(!Number.isInteger(c.revision)||c.types.length!==2||c.hanging.length>100||c.anti.length>100)throw Error('INVALID_TAGS');for(const group of ['types','hanging','anti'] as const){if(new Set(c[group].map(m=>m.key)).size!==c[group].length||c[group].some(m=>!initialTags[group].some(v=>v.key===m.key)&&(group==='types'||!/^custom_[a-f0-9]{12}$/.test(m.key))))throw Error('INVALID_KEYS');}for(const m of c.hanging){if(!m.sizes.length||m.sizes.length>4||new Set(m.sizes.map(s=>s.id)).size!==m.sizes.length||m.sizes.some(s=>!['small','medium','large','miniature'].includes(s.id)||typeof s.active!=='boolean'||!s.name_en.trim()||!s.name_es.trim()))throw Error('INVALID_TAG_SIZES');}for(const v of [...c.types,...c.hanging,...c.anti]){if(!v.name_en.trim()||!v.name_es.trim()||v.name_en.length>100||v.name_es.length>100||typeof v.active!=='boolean'||(v.deleted!==undefined&&typeof v.deleted!=='boolean')||(v.deleted&&v.active)||!Number.isInteger(v.display_order)||v.display_order<0||v.display_order>100||!/^\/icons\/[a-z0-9-]+\.svg$|^closures\/uploads\/[a-f0-9-]+-[0-9]+\.webp$/.test(v.icon))throw Error('INVALID_TAG');}for(const s of [...c.hanging.flatMap(m=>m.sizes),...c.anti])if(!Number.isFinite(s.width)||!Number.isFinite(s.height)||s.width<=0||s.height<=0||s.width>20||s.height>20)throw Error('INVALID_DIMENSIONS');const seen=new Set();for(const m of c.mapping){const key=m.size+':'+m.width;if(!validPair(m.size,m.width)||seen.has(key)||!c.anti.some(a=>a.key===m.model)||(antiRibbonWidths[m.model]!==undefined&&(m.width!==antiRibbonWidths[m.model]||!initialTags.mapping.some(v=>v.model===m.model&&v.size===m.size&&v.width===m.width))))throw Error('INVALID_MAPPING');seen.add(key);}return c;}

export function tagAwaitingSize(c:TagsConfig,i:Item){return i.tag_type==='hanging'&&!i.tagSize&&tagTypeAvailable(c,i.tag_type,i)&&c.hanging.some(m=>m.key===i.tagShape&&m.active&&!m.deleted&&m.sizes.some(s=>s.active));}
