import {describe,it,expect} from 'vitest';
import {blankItem,type Order} from './model';
import {getCollarDetailRows,getCollarSummary,getOrderPresentation,getTagPreview,getSummaryRows,readablePhone} from './presentation';
import {getCollarConfiguration} from './configuration';
import {fixtureDesigns,fixtureFonts} from '../data/fixtures';
describe('common projections',()=>{
 it('removes only regenerated decoration metadata from visible instructions',()=>{const item={...blankItem(),personalization_type:'decoration' as const,decorationIcon:'heart' as const,tag_phone:'+15551234567',personalization_notes:'Name decoration: heart\nInformation icons: phone\nPlease engrave gently'};expect(getCollarSummary(item,'en').notes).toBe('Please engrave gently');});
 it('keeps localized fact rows separate and excludes missing categories',()=>{const item={...blankItem(),pet_name:'Pipo',tagEmail:'hello@example.com',tagExtras:{selected:['address','family','neutered'] as const,address:'Quito',health:'',neutered:'Neutered',familyName:'Antonela Suarez',familyPhone:'0958764197',other:''}};const value={...item,tagExtras:{...item.tagExtras,selected:[...item.tagExtras.selected]}};const rows=getSummaryRows(value,'es','CH-17-1');expect(rows.tag.find(r=>r.key==='address')).toMatchObject({label:'Dirección',value:'Quito'});expect(rows.tag.find(r=>r.key==='family')?.value).toBe('Antonela Suarez\n0958764197');expect(rows.tag.some(r=>r.key==='health'||r.key==='extra')).toBe(false);expect(rows.collar[0].label).toBe('Diseño');});
 it('shares collar facts across review and confirmation while allowing context-specific omissions',()=>{const item={...blankItem(),pet_name:'Pipo',personalization_type:'decoration' as const,decorationIcon:'paw' as const,tagExtras:{selected:['family'] as ('family')[],familyName:'Ana',familyPhone:'0991234567',address:'',health:'',neutered:'',other:''}};const review=getCollarDetailRows(item,'es','CH-1'),confirmation=getCollarDetailRows(item,'es','CH-1',{includePetName:false,includeEmptyExtra:false,includeNotesInTag:false});expect(review.collar).toEqual(confirmation.collar);expect(review.tag.find(row=>row.key==='name')?.value).toBe('Pipo');expect(confirmation.tag.some(row=>row.key==='name')).toBe(false);expect(confirmation.tag.find(row=>row.key==='family')?.value).toBe('Ana\n0991234567');expect(confirmation.font.value).toBe(String(item.font_number).padStart(2,'0'));expect(confirmation.personalization.value).toBe('Decoración · Huella');});
 it('review, production, exports and preview retain every real tag detail',()=>{
  const item={...blankItem(),pet_name:'Maximiliano Rodriguez',tag_phone:'+491756461669',tagEmail:'hello@example.com',tagExtras:{selected:['address','health','neutered','family','phones','other'] as const,address:'A long address',health:'Allergies and medication',neutered:'Spayed',familyName:'Ana',familyPhone:'+1 555 111 2233',phones:'+491756461669\n+1 555 888 9999',other:'Humberto Salvador'}};
  const value={...item,tagExtras:{...item.tagExtras,selected:[...item.tagExtras.selected]}};
  const summary=getCollarSummary(value,'en');expect(summary.tag.extras).toHaveLength(7);expect(getCollarSummary(getCollarConfiguration(value),'en')).toEqual(summary);
  const order:Order={id:'order',status:'new',confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString(),items:[{...value,design:fixtureDesigns[0],font:fixtureFonts[0]}],customer_snapshot:{name:'Ana',phone:'1234567'},order_code:'COLTI'};
  expect(getOrderPresentation(order,'en').collars[0].tag).toEqual(summary.tag);
  const preview=getTagPreview(value,'en');expect(preview.lines.find(l=>l.key==='health')?.value).toBe('Allergies and medication');expect(preview.lines.find(l=>l.key==='phones')?.value).toContain('+49 175 646 1669');expect(preview.lines.find(l=>l.key==='email')?.value).toBe('hello@example.com');
 });
 it('omits absent optional details and formats phone without changing storage',()=>{const item=blankItem();item.tag_phone='+491756461669';expect(getCollarSummary(item,'en').tag.extras).toEqual([]);expect(readablePhone(item.tag_phone)).toBe('+49 175 646 1669');expect(item.tag_phone).toBe('+491756461669');});
 it.each(['none','decoration'] as const)('preserves legacy production notes for %s',personalization_type=>{const item={...blankItem(),personalization_type,personalization_notes:'Legacy engraving instructions'};expect(getCollarSummary(item,'en').notes).toBe(item.personalization_notes);expect(getCollarSummary(getCollarConfiguration(item),'en').notes).toBe(item.personalization_notes);});
});

it.each([['Spayed','Esterilizada'],['Neutered','Castrado']])('localizes %s without changing stored values',(stored,translated)=>{const item=blankItem();item.tagExtras={selected:['neutered'],address:'',health:'',neutered:stored,familyName:'',familyPhone:'',other:''};expect(getCollarSummary(item,'es').tag.extras[0].value).toBe(translated);expect(getCollarSummary(item,'en').tag.extras[0].value).toBe(stored);expect(item.tagExtras.neutered).toBe(stored);});

it('decorates family name and phone separately without changing stored contact data',()=>{
 const item={...blankItem(),personalization_type:'decoration' as const,tagExtras:{selected:['family','phones'] as ('family'|'phones')[],familyName:'Ana',familyPhone:'0992826805',phones:'0984156889\n0999999999',address:'',health:'',neutered:'',other:''}};
 const lines=getTagPreview(item,'es').lines;expect(lines.find(l=>l.key==='family-name')).toMatchObject({value:'Ana',icon:'user'});expect(lines.find(l=>l.key==='family-phone')).toMatchObject({value:'0992826805',icon:'phone'});expect(lines.find(l=>l.key==='phones')?.icon).toBe('phone');
 expect(getTagPreview({...item,personalization_type:'none'},'es').lines.filter(l=>l.key.startsWith('family')||l.key==='phones').every(l=>!l.icon)).toBe(true);expect(getCollarSummary(item,'es').tag.extras.find(e=>e.key==='family')?.value).toBe('Ana\n0992826805');
});
