import {test,expect} from './fixture-catalog';
import {mkdir} from 'node:fs/promises';
for(const width of [390,834,1440])for(const shape of ['paw','circle','bone','military','anti-fall']){
 test(`${shape} preview fits long real details at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000});await page.goto('/');await page.evaluate(async shape=>{
   const model='/src/domain/model.ts',rules='/src/domain/rules.ts';const {blankDraft}=await import(model),{getAvailableTagSizes}=await import(rules);const d=blankDraft();d.step='personalization';
   const size=getAvailableTagSizes(shape)[0];Object.assign(d.current,{tag_type:shape==='anti-fall'?'anti_fall':'hanging',tagShape:shape==='anti-fall'?undefined:shape,tagSize:size?.id,tagWidthCm:size?.width,tagHeightCm:size?.height,pet_name:'Maximiliano Rodriguez',tag_phone:'+491756461669',tagEmail:'household.contact.household.contact.household.contact.household.contact.household.contact.family@pets.example.com',font_number:9,personalization_type:'decoration',decorationIcon:'heart',tagExtras:{selected:['address','health','neutered','family','phones'],address:'Avenida de los Jardines 123, edificio Primavera, apartamento 42, Miami, Florida. '.repeat(3),health:'Allergies, medication: needs daily treatment. Problemas gastricos. '.repeat(7),neutered:'Spayed',familyName:'Humberto Salvador',familyPhone:'+1 555 123 4567',phones:'+1 555 987 6543\n+49 175 888 9999',other:''}});sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));
  },shape);await page.reload();const preview=page.locator('.tag-face-preview');await expect(preview).toBeVisible();if(shape!=='anti-fall')await page.getByRole('button',{name:'View back',exact:true}).click();await expect(page.locator('.tag-face-line')).toHaveCount(shape==='bone'||shape==='anti-fall'?3:4);await expect(page.locator('.tag-preview-disclaimer')).toContainText('include all the details');expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('colti-draft-v1')!).current.tagEmail)).toContain('family@pets.example.com');await page.evaluate(()=>document.fonts.ready);
  await expect.poll(()=>preview.evaluate(root=>Array.from(root.querySelectorAll('.tag-face-content')).every(box=>{const b=box.getBoundingClientRect(),parent=box.parentElement!.getBoundingClientRect();return b.left>=parent.left&&b.right<=parent.right+.5&&b.top>=parent.top&&b.bottom<=parent.bottom+.5;}))).toBe(true);
  // Check painted bounds: transforms do not change intrinsic scrollWidth.
  await expect.poll(()=>preview.evaluate(root=>Array.from(root.querySelectorAll('.tag-face-content')).every(box=>{const b=box.getBoundingClientRect();return Array.from(box.querySelectorAll('.tag-detail-text,.tag-info-unit svg')).every(node=>{const r=node.getBoundingClientRect();return r.left>=b.left-.5&&r.right<=b.right+.5&&r.top>=b.top-.5&&r.bottom<=b.bottom+.5;});}))).toBe(true);
  await expect.poll(()=>preview.evaluate(root=>Array.from(root.querySelectorAll('.tag-face-content')).every(box=>box.scrollHeight<=box.clientHeight+1||box.classList.contains('tag-content-scroll')))).toBe(true);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await mkdir('artifacts/block-c',{recursive:true});await preview.screenshot({path:`artifacts/block-c/${shape}-${width}.png`});
 });
}
test('legacy upload draft resumes in the reusable accordion and counters match the engine',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const path='/src/domain/model.ts';const {blankDraft}=await import(path);const d=blankDraft();sessionStorage.setItem('colti-draft-v1',JSON.stringify({...d,version:2,step:13}));});await page.reload();await expect(page.getByRole('heading',{name:'A little extra personality?'})).toBeVisible();await expect(page.locator('.progress-meta')).toContainText('9 / 10');await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','90');
});
test('Hanging shape and size stay together, restore correctly, and Anti-fall skips them',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const path='/src/domain/model.ts';const {blankDraft}=await import(path);const d=blankDraft();d.step='tag-type';d.current.size_code='M';d.current.width_cm=2.5;d.current.pet_name='Lola';d.current.tag_phone='+1 555 123 4567';sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));});await page.reload();
 const next=page.getByRole('button',{name:'Continue →',exact:true});await next.click();await expect(page.getByRole('heading',{name:'Choose the tag shape.'})).toBeVisible();await expect(page.locator('.progress-meta')).toContainText('4 / 10');await expect(next).toBeDisabled();
 await page.getByRole('button',{name:'Circle',exact:true}).click();await expect(page.getByRole('button',{name:'Medium 2.5 × 2.5 cm',exact:true})).toHaveAttribute('aria-pressed','true');await expect(next).toBeEnabled();await page.reload();await expect(page.getByRole('heading',{name:'Choose the tag shape.'})).toBeVisible();await expect(next).toBeEnabled();
 await page.getByRole('button',{name:'Bone',exact:true}).click();await expect(next).toBeDisabled();await expect(page.locator('.tag-size-grid .option')).toHaveCount(3);await page.getByRole('button',{name:'Medium 2.7 × 4 cm',exact:true}).click();await next.click();await expect(page.locator('input.big-input')).toHaveValue('Lola');
 await page.getByRole('button',{name:'← Back',exact:true}).click();await expect(page.getByRole('heading',{name:'Choose the tag shape.'})).toBeVisible();await page.getByRole('button',{name:'← Back',exact:true}).click();await page.getByRole('button',{name:'Anti-fall',exact:true}).click();await next.click();await expect(page.locator('input.big-input')).toHaveValue('Lola');await expect(page.locator('.tag-shape-grid')).toHaveCount(0);await expect(page.locator('.progress-meta')).toContainText('5 / 10');
});
