import {test,expect} from './fixture-catalog';
import {mkdir} from 'node:fs/promises';
for(const [width,height] of [[1440,900],[1366,768],[1194,834],[834,1194],[390,844],[320,740]])for(const count of [1,2,3])test(`confirmation fact tables ${width}, ${count} collars`,async({page})=>{
 await page.setViewportSize({width,height});await page.goto('/');await page.evaluate(async({count})=>{const model='/src/domain/model.ts',fixtures='/src/data/fixtures.ts';const {blankDraft,blankItem}=await import(model),{fixtureDesigns}=await import(fixtures);const d=blankDraft();d.customer={name:'Juana Antonela Suarez Rodriguez',phone:'+491756461669'};d.step='order-summary';d.items=Array.from({length:count},(_,index)=>({...blankItem(),size_code:'M',width_cm:2.5,design_id:fixtureDesigns[0].id,collar_type:'metal_buckle',tag_type:index%2?'anti_fall':'hanging',tagShape:'bone',tagSize:'medium',tagWidthCm:2.7,tagHeightCm:4,pet_name:'Maximiliano Rodriguez',tag_phone:d.customer.phone,font_number:[28,9,33][index],personalization_type:index===0?'decoration':'none',decorationIcon:index===0?'heart':undefined,tagEmail:'hello@example.com',tagExtras:{selected:['address','family','neutered','health','phones'],address:'Quito, una dirección larga para verificar el ancho disponible',health:'Allergies',neutered:'Neutered',familyName:'Antonela Suarez',familyPhone:'0958764197',phones:'+15551234567',other:''}}));sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));},{count});await page.reload();await page.getByRole('button',{name:'Save order'}).click();;
 await expect(page.locator('.confirmation-customer .eyebrow')).toHaveText('CUSTOMER');await expect(page.locator('.local-demo-indicator')).toHaveCount(0);await expect(page.locator('.confirmation-order-meta time')).toHaveCount(0);await expect(page.locator('.confirmation-date time')).not.toHaveText(/\d+:\d+:\d+/);await expect(page.getByRole('heading',{name:'YOUR ORDER',exact:true})).toBeVisible();const headers=page.locator('.confirmation-collars .collar-collapse-toggle');await expect(headers).toHaveCount(count);for(const header of await headers.all())await expect(header).toHaveAttribute('aria-expanded','false');await headers.first().click();
 const first=page.locator('.order-collar-summary').first();await expect(first.locator('.confirmation-detail-tag dt').filter({hasText:'Pet name'})).toHaveCount(0);await expect(first.locator('.confirmation-detail-tag dt').filter({hasText:'Family contact'})).toBeVisible();await expect(first.getByText('Extra text',{exact:true})).toHaveCount(0);await expect(first.locator('.confirmation-detail-lettering').getByText('No personalization')).toHaveCount(0);
 await expect(first.locator('.confirmation-detail-lettering .fitted-lettering')).toHaveCount(0);const preview=page.locator('.collar-collapse-label .fitted-lettering').first();await preview.scrollIntoViewIfNeeded();await expect.poll(()=>preview.evaluate(el=>getComputedStyle(el).fontFamily)).toContain('colti-font-28-');for(const selector of ['.confirmation-detail-collar','.confirmation-detail-tag','.confirmation-detail-lettering']){const row=first.locator(selector+' .summary-facts>div').first();await expect(row).toHaveCSS('display','flex');await expect(row).toHaveCSS('border-bottom-width','0px');}
 const collar=await first.locator('.confirmation-detail-collar').boundingBox(),tag=await first.locator('.confirmation-detail-tag').boundingBox(),lettering=await first.locator('.confirmation-detail-lettering').boundingBox();await expect(first.locator('.confirmation-detail-collar .order-collar-image')).toHaveCount(1);if(width<=390){expect(tag!.y).toBeGreaterThanOrEqual(collar!.y+collar!.height-1);}else{expect(Math.abs(collar!.y-tag!.y)).toBeLessThan(2);}expect(lettering!.y).toBeGreaterThan(Math.max(collar!.y+collar!.height,tag!.y+tag!.height)-1);await headers.first().focus();await page.keyboard.press('Enter');await expect(headers.first()).toHaveAttribute('aria-expanded','false');await page.keyboard.press('Enter');await expect(headers.first()).toHaveAttribute('aria-expanded','true');

 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const buttons=page.locator('.downloads button');expect(await buttons.nth(0).evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(await buttons.nth(1).evaluate(el=>getComputedStyle(el).backgroundColor));
 if(count===3){await page.evaluate(()=>{document.querySelectorAll<HTMLElement>('.configurator-area,.flow').forEach(el=>el.scrollTop=0);window.scrollTo(0,0);});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>undefined)));});await mkdir('artifacts/confirmation-final',{recursive:true});await page.screenshot({path:`artifacts/confirmation-final/${width}.png`,fullPage:true});}
 await expect(async()=>{const restart=page.getByRole('button',{name:'Start a new order'});if(await restart.isVisible())await restart.click();await expect(page.getByRole('heading',{name:'First, what’s your name?'})).toBeVisible({timeout:200});}).toPass();
});
