import {test,expect} from '@playwright/test';
test('confirmed local order reaches Admin and survives refresh without duplicate imports',async({page})=>{
 const stored:Record<string,unknown>[]=[];
 await page.route('http://127.0.0.1:4174/api/admin/local-orders/**',async route=>{const request=route.request();if(request.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});if(request.method()==='GET')return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173'},body:JSON.stringify({overrides:[],hero:{revision:0,images:[]}})});const orders=request.postDataJSON().orders;for(const order of orders)if(!stored.some(p=>p.id===order.id))stored.push(order);await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5173'},body:JSON.stringify({added:orders.length})});});
 await page.goto('/');
 const id=await page.evaluate(async()=>{const backendPath='/src/infrastructure/supabaseRepositories.ts',modelPath='/src/domain/model.ts',fixturesPath='/src/data/fixtures.ts';const backend=await import(backendPath),model=await import(modelPath),fixtures=await import(fixturesPath);const catalog=await backend.loadCatalog();const design=catalog.designs.find(d=>d.active&&d.compatibility.some(c=>c.size_code==='M'&&c.width_cm===2.5));const d=model.blankDraft();d.customer={name:'Bridge test customer',phone:'0984156889'};d.items=[{...model.blankItem(),size_code:'M',width_cm:2.5,design_id:design.id,pet_name:'Bridge test pet',tag_type:'anti_fall',tag_phone:'0984156889',font_number:9}];return (await backend.confirmOrder(d)).id;});
 await expect.poll(()=>stored.length).toBe(1);expect(stored[0].id).toBe(id);await page.reload();await expect.poll(()=>stored.length).toBe(1);
 await page.route('**/src/data/adminBackend.ts*',async route=>{await route.fulfill({contentType:'text/javascript',body:`import {createAdminApplication} from '/src/application/admin.ts';import {createDriveConnection} from '/src/application/driveConnection.ts';import {driveHttpRepository} from '/src/infrastructure/driveConnection.ts';const repo={authorized:async()=>true,list:async(search,status)=>fetch('/api/admin/local-orders').then(r=>r.json()).then(orders=>orders.filter(o=>!status||o.status===status))};export const admin=createAdminApplication(repo,{load:()=>[]});export const mode='live';export const adminAuth={subscribe:()=>()=>{}};export const driveConnection=createDriveConnection(driveHttpRepository,repo.authorized);`});});
 await page.route('**/api/admin/local-orders',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(stored)}));await page.goto('/admin/orders');await expect(page.getByRole('heading',{name:'Bridge test pet',exact:true})).toBeVisible();await expect(page.getByText('Bridge test customer',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Bridge test pet',exact:true})).toBeVisible();
});
