import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function fixture(page:Page,transform=(s:string)=>s){const body=transform(await readFile('tests/fixtures/admin-backend.js','utf8'));await page.route('**/src/data/adminBackend.ts*',r=>r.fulfill({contentType:'text/javascript',body}));}
for(const count of [1,5,10])test(`${count} collars use bounded previews and a wide detail modal`,async({page})=>{
 await fixture(page,s=>s.replace("['Luna','Sol']",`Array.from({length:${count}},(_,n)=>'Pet '+n)`));await page.setViewportSize({width:1440,height:900});await page.goto('/admin/orders');const card=page.locator('.admin-ticket');await expect(card).toHaveCount(1);await expect(card.locator('.design-image')).toHaveCount(count>4?3:count);await expect(card.locator('.admin-more-images')).toHaveCount(count>4?1:0);
 await page.getByRole('button',{name:'New',exact:true}).click();await page.getByLabel('Search orders').fill('Pet');await page.getByRole('button',{name:'Open order COLTI-US-0024'}).click();const modal=page.getByRole('dialog',{name:'Order details'});await expect(modal).toBeVisible();await expect(modal.locator('.admin-collar')).toHaveCount(count);expect((await modal.boundingBox())!.width).toBeGreaterThan(1000);await page.screenshot({path:`artifacts/admin/modal-${count}.png`});await page.getByRole('button',{name:'Close order'}).click();await expect(page.getByLabel('Search orders')).toHaveValue('Pet');await expect(page.getByRole('button',{name:'New',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.admin-order-dialog')).toHaveCount(0);
});
test('catalog bulk action confirms its scope and preserves width overrides',async({page})=>{
 await fixture(page);await page.goto('/admin/catalog');await expect(page.locator('.admin-design-card')).toHaveCount(1);await page.getByLabel('Size',{exact:true}).selectOption('XS');await page.getByLabel('1.5 cm · CH-17-1',{exact:true}).uncheck();await page.getByRole('button',{name:'Disable all',exact:true}).click();const modal=page.getByRole('dialog',{name:'Confirm catalog changes'});await expect(modal).toContainText('Woven · XS · Whole designs');await page.screenshot({path:'artifacts/admin/catalog-bulk-confirmation.png'});await page.getByRole('button',{name:'Confirm changes'}).click();await expect(modal).toHaveCount(0);await expect(page.getByLabel('Whole design · CH-17-1')).not.toBeChecked();await page.getByRole('button',{name:/INACTIVE/}).click();await expect(page.locator('.admin-design-card')).toHaveCount(1);await page.screenshot({path:'artifacts/admin/catalog-inactive.png',fullPage:true});await page.getByRole('button',{name:'Enable all',exact:true}).click();await page.getByRole('button',{name:'Confirm changes'}).click();await page.getByRole('button',{name:/ALL/}).click();await expect(page.getByLabel('Whole design · CH-17-1')).toBeChecked();await expect(page.getByLabel('1.5 cm · CH-17-1')).not.toBeChecked();
});
test('hero edits survive refresh signals and reactivate at the end',async({page})=>{
 await fixture(page);await page.goto('/admin/hero');const active=page.getByRole('region',{name:'ACTIVE hero photos',exact:true}),inactive=page.getByRole('region',{name:'INACTIVE hero photos',exact:true});await expect(active.locator('article')).toHaveCount(6);await page.getByLabel('Activate 0.png',{exact:true}).uncheck();await expect(inactive.locator('article')).toHaveCount(1);await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByText('Saved',{exact:true})).toBeVisible();await page.reload();await expect(inactive.locator('article')).toHaveCount(1);await page.getByLabel('Activate 0.png',{exact:true}).check();await expect(active.locator('article').last().getByRole('heading')).toHaveText('0.png');await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Discard changes',exact:true}).click();await expect(inactive.locator('article')).toHaveCount(1);
});
for(const width of [1440,834,390])test(`professional login at ${width} retains accessible form and protected routes`,async({page})=>{
 await fixture(page,s=>s.replace('authorized:async()=>true','authorized:async()=>false'));await page.setViewportSize({width,height:900});await page.goto('/admin/login');await expect(page.getByRole('heading',{name:'Sign in to COLTI'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Administration'})).toHaveCount(0);await expect(page.getByLabel('Email address')).toHaveAttribute('autocomplete','username');const password=page.locator('input[autocomplete="current-password"]');await expect(password).toHaveAttribute('type','password');await page.getByRole('button',{name:'Show password'}).click();await expect(password).toHaveAttribute('type','text');await page.getByRole('button',{name:'Hide password'}).click();await expect(password).toHaveAttribute('type','password');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`artifacts/admin/login-${width}.png`,fullPage:true});
});
