import {test,expect,type Page} from '@playwright/test';
const screens=[{name:'desktop',width:1440,height:900},{name:'tablet',width:834,height:1194},{name:'mobile',width:390,height:844}];
test.use({launchOptions:{args:['--disable-gpu','--force-color-profile=srgb']}});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{const Original=Date;class FixedDate extends Original{constructor(...args:any[]){super(args.length?args[0]:'2026-10-03T12:00:00Z');}static now(){return new Original('2026-10-03T12:00:00Z').getTime();}}window.Date=FixedDate as DateConstructor;});});
async function seed(page:Page,step:string,shape='anti-fall',font=9){
 await page.goto('/');await page.evaluate(async({step,shape,font})=>{
 const model='/src/domain/model.ts',catalog='/src/catalog/drive.ts',rules='/src/domain/rules.ts';const {blankDraft,blankItem}=await import(model),{driveDesigns}=await import(catalog),{getAvailableTagSizes}=await import(rules);const d=blankDraft(),design=driveDesigns.find((x:any)=>x.active&&x.type==='woven'&&x.compatibility.some((c:any)=>c.size_code==='M'&&Number(c.width_cm)===2.5)),size=getAvailableTagSizes(shape)[0];d.customer={name:'Antonela Suarez',phone:'0984156889'};d.step=step;
 Object.assign(d.current,{size_code:'M',width_cm:2.5,design_id:design.id,collar_type:'metal_buckle',tag_type:shape==='anti-fall'?'anti_fall':'hanging',tagShape:shape==='anti-fall'?undefined:shape,tagSize:size?.id,tagWidthCm:size?.width,tagHeightCm:size?.height,pet_name:'Mona',tag_phone:'0984156889',font_number:font,personalization_type:'decoration',decorationIcon:'heart',tagExtras:{selected:['address','neutered','phones'],address:'Quito',neutered:'Neutered',phones:'0992826805\n0984156889',health:'',familyName:'Ana',familyPhone:'0992826805',other:''}});
 if(step==='order-summary')d.items=[structuredClone(d.current),{...structuredClone(d.current),id:blankItem().id,pet_name:'Luna Sol',font_number:28,personalization_type:'none',decorationIcon:undefined}];sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));
 },{step,shape,font});await page.reload();
}
async function settled(page:Page){
 await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>{const r=i.getBoundingClientRect();return i.getAttribute('src')&&r.bottom>0&&r.top<innerHeight&&r.width>0;}).map(i=>i.decode()));await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>undefined)));});
 await expect(page.getByText(/Real font unavailable|Fuente real no disponible/)).toHaveCount(0);
 await expect.poll(()=>page.locator('.fitted-lettering').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect(),dialog=document.querySelector('dialog[open]');let top=Math.max(0,r.top),bottom=Math.min(innerHeight,r.bottom);for(let p=n.parentElement;p;p=p.parentElement){if(getComputedStyle(p).overflowY!=='visible'){const b=p.getBoundingClientRect();top=Math.max(top,b.top);bottom=Math.min(bottom,b.bottom);}}return (!dialog||dialog.contains(n))&&r.width>0&&bottom>top;}).every(n=>{const family=getComputedStyle(n).fontFamily;return family.includes('colti-font-')&&document.fonts.check(`24px ${family}`);}))).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
}
async function snap(page:Page,name:string){
 await page.evaluate(()=>{document.querySelectorAll<HTMLElement>('.configurator-area,.flow').forEach(n=>n.scrollTop=0);window.scrollTo(0,0);});await page.locator('.configurator-area').scrollIntoViewIfNeeded();await settled(page);if(name.endsWith('personalization-closed'))await page.evaluate(()=>window.scrollTo(0,0));
 await expect.soft(page).toHaveScreenshot(name+'.png',{animations:'disabled',caret:'hide',scale:'css',threshold:0.01,maxDiffPixels:10});
}
async function focused(page:Page,selector:string,name:string){await page.locator(selector).first().scrollIntoViewIfNeeded();await settled(page);await expect.soft(page).toHaveScreenshot(name+'.png',{animations:'disabled',caret:'hide',scale:'css',threshold:0.01,maxDiffPixels:10});}
for(const screen of screens){
 test(`${screen.name} approved states`,async({page})=>{
 test.setTimeout(180000);await page.setViewportSize(screen);
 const shot=(name:string)=>snap(page,screen.name+'-'+name);
 for(const step of ['size','fastening','tag-type','tag-shape','tag-details','lettering','review']){await seed(page,step,step==='tag-shape'?'paw':'anti-fall');await shot(step);if(step==='tag-details')await focused(page,'.contact-fields',screen.name+'-family-numbers');if(step==='review')await focused(page,'.collar-review-lettering',screen.name+'-review-lettering');}
 await seed(page,'design');await expect(page.locator('.design-card').first()).toBeVisible();await shot('catalog-woven');await page.getByRole('tab',{name:'PRINTED',exact:true}).click();await shot('catalog-printed');await page.locator('.design-card .image-button').first().click();await shot('catalog-modal');await page.keyboard.press('Escape');
 await seed(page,'lettering');await settled(page);await page.locator('.lettering-view-all').click();for(const card of await page.locator('.lettering-grid .lettering-card').all()){await card.scrollIntoViewIfNeeded();await expect.poll(()=>card.locator('.fitted-lettering').evaluate(n=>getComputedStyle(n).fontFamily)).toContain('colti-font-');}await page.locator('.lettering-scroll').evaluate(n=>n.scrollTop=0);await shot('fonts-modal');await page.getByRole('button',{name:'Font 17',exact:true}).click();await shot('fonts-selected-17');await page.keyboard.press('Escape');
 for(const shape of ['anti-fall','paw','circle','bone','military']){await seed(page,'personalization',shape);await expect(page.locator('.original-tag-face img')).toHaveAttribute('src',/^data:/);await shot('preview-'+shape+'-front');if(shape!=='anti-fall'){await page.getByRole('button',{name:'View back',exact:true}).click();await shot('preview-'+shape+'-back');}}
 await seed(page,'personalization');await page.locator('#personality-toggle-decoration').click();await shot('personalization-closed');
 for(const mode of ['drawing','dog_photo']){await page.locator('#personality-toggle-'+mode).click();await shot('personalization-'+mode);await page.locator('#personality-toggle-'+mode).click();}
 await page.locator('#personality-toggle-drawing').click();await page.locator('#personality-drawing input[type=file]').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await expect(page.getByRole('alert')).toBeVisible();await shot('personalization-upload-error');await page.locator('#personality-toggle-dog_photo').click();const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=80;c.height=60;const x=c.getContext('2d')!;x.fillStyle='#f4d9e8';x.fillRect(0,0,80,60);x.fillStyle='#452638';x.fillRect(20,10,40,40);return c.toDataURL('image/png').split(',')[1];});await page.locator('#personality-dog_photo input[type=file]').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await expect(page.getByText('✓ Image uploaded')).toBeVisible();await shot('personalization-photo-uploaded');
 await page.locator('#personality-toggle-none').click();await shot('personalization-none');
 await seed(page,'order-summary');await shot('your-order-closed');await page.locator('.collar-collapse-toggle').first().click();await shot('your-order-expanded');await page.getByRole('button',{name:'Save order',exact:true}).click();await expect(page.getByRole('heading',{name:'DEMO-COLTI-US-0001'})).toBeVisible();await shot('confirmation-closed');await page.locator('.confirmation-collars .collar-collapse-toggle').first().click();await shot('confirmation-expanded');
 });
 test(`${screen.name} Spanish key states`,async({page})=>{
 test.setTimeout(90000);await page.setViewportSize(screen);
 for(const step of ['design','lettering','review','order-summary']){await seed(page,step);await page.getByRole('button',{name:'Cambiar a español'}).click();await snap(page,screen.name+'-es-'+step);}
 await page.getByRole('button',{name:'Realizar pedido',exact:true}).click();await expect(page.getByRole('heading',{name:'DEMO-COLTI-US-0001'})).toBeVisible();await snap(page,screen.name+'-es-confirmation-closed');await page.locator('.confirmation-collars .collar-collapse-toggle').first().click();await snap(page,screen.name+'-es-confirmation-expanded');
 });
 test(`${screen.name} font failure is explicitly reported`,async({page})=>{
 await page.setViewportSize(screen);await page.route('**/fonts/plates/*',r=>r.abort());await seed(page,'lettering');await expect(page.getByText('Real font unavailable — neutral preview shown').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect.soft(page).toHaveScreenshot(screen.name+'-font-error.png',{animations:'disabled',caret:'hide',scale:'css',threshold:0.01,maxDiffPixels:10});
 });
 test(`${screen.name} Drive loading reserves geometry`,async({page})=>{
 await page.setViewportSize(screen);let release!:()=>void;const ready=new Promise<void>(r=>release=r);await page.route('**/catalog/drive/*',async route=>{await ready;await route.continue();});await seed(page,'design');const card=page.locator('.design-card .image-button').first();await expect(card).toBeVisible();const before=await card.boundingBox(),hero=await page.locator('.story').boundingBox();release();await expect.poll(()=>page.locator('.design-card img').first().evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true);const after=await card.boundingBox(),nextHero=await page.locator('.story').boundingBox();expect(after).toEqual(before);expect(nextHero).toEqual(hero);expect(Math.abs(after!.width-after!.height)).toBeLessThan(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 });
}
