import {test,expect,type Page} from './fixture-catalog';
import {mkdir} from 'node:fs/promises';
test('repetitive pet eyebrow is absent, contextual eyebrows and lazy fonts remain',async({page})=>{
 const plates:string[]=[];page.on('request',request=>{if(request.url().includes('/fonts/plates/'))plates.push(request.url());});await page.goto('/');await expect(page.getByRole('heading',{name:'First, what’s your name?'})).toBeVisible();expect(plates).toEqual([]);
 for(const step of ['tag-phone','tag-details','lettering','personalization','review']){await draft(page,step,9);await expect(page.locator('.flow-title>.eyebrow')).toHaveCount(0);}
 await draft(page,'width');await expect(page.locator('.flow-title>.eyebrow')).toHaveText('YOUR SELECTED SIZE · XS');await draft(page,'pet-name');await expect(page.locator('.flow-title>.eyebrow')).toHaveText('FOR THE ID TAG');
});
async function draft(page:Page,step:string,font=9,name='Pipo',two=false){
 await page.goto('/');await page.evaluate(async ({step,font,name,two})=>{
  const model='/src/domain/model.ts',fixtures='/src/data/fixtures.ts';const {blankDraft,blankItem}=await import(model),{fixtureDesigns}=await import(fixtures);const d=blankDraft();d.customer={name:'Martin Wonejek',phone:'+491756461669'};d.step=step;
  Object.assign(d.current,{size_code:step==='width'?'XS':'M',width_cm:step==='width'?1.5:2.5,design_id:fixtureDesigns[0].id,collar_type:'metal_buckle',tag_type:'hanging',tagShape:'bone',tagSize:'medium',tagWidthCm:2.7,tagHeightCm:4,pet_name:name,tag_phone:d.customer.phone,font_number:font,personalization_type:'decoration',decorationIcon:'heart',tagEmail:'hello@example.com',tagExtras:{selected:['address','family','neutered','health','phones'],address:'Quito',familyName:'Antonela Suarez',familyPhone:'0958764197',neutered:'Neutered',health:'Allergies',phones:'+15551234567',other:''}});
  if(step==='order-summary'){d.items=[structuredClone(d.current)];if(two)d.items.push({...structuredClone(d.current),id:blankItem().id,pet_name:'Maximiliano Rodriguez',font_number:33,design_id:fixtureDesigns[1].id,personalization_type:'none',decorationIcon:undefined});}
  sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));
 },{step,font,name,two});await page.reload();
}
async function realFont(page:Page,selector:string,number:number){const sample=page.locator(selector).first();await sample.scrollIntoViewIfNeeded();await expect.poll(()=>sample.evaluate(node=>getComputedStyle(node).fontFamily)).toContain(`colti-font-${number}-`);await expect.poll(()=>sample.evaluate(node=>document.fonts.check(`24px ${getComputedStyle(node).fontFamily}`))).toBe(true);}
test('five saved collars stay compact and independently expand by keyboard',async({page})=>{
 await page.setViewportSize({width:390,height:844});await draft(page,'order-summary');await page.evaluate(()=>{const d=JSON.parse(sessionStorage.getItem('colti-draft-v1')!);d.items=Array.from({length:5},(_,index)=>({...structuredClone(d.items[0]),id:crypto.randomUUID(),pet_name:`Pipo ${index+1}`}));sessionStorage.setItem('colti-draft-v1',JSON.stringify(d));});await page.reload();await page.getByRole('button',{name:'Save order'}).click();const headers=page.locator('.confirmation-collars .collar-collapse-toggle');await expect(headers).toHaveCount(5);await expect(headers.first()).toHaveAttribute('aria-expanded','false');for(let index=1;index<5;index++)await expect(headers.nth(index)).toHaveAttribute('aria-expanded','false');await headers.nth(3).focus();await page.keyboard.press('Enter');await expect(headers.nth(3)).toHaveAttribute('aria-expanded','true');await page.keyboard.press('Enter');await expect(headers.nth(3)).toHaveAttribute('aria-expanded','false');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await realFont(page,'.confirmation-collars .fitted-lettering',9);await shot(page,'confirmation-five-collars');
});
async function shot(page:Page,name:string){await page.evaluate(()=>{document.querySelectorAll<HTMLElement>('.configurator-area,.flow').forEach(node=>node.scrollTop=0);window.scrollTo(0,0);});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.getAttribute('src')).map(i=>{i.loading='eager';return i.decode();}));await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>undefined)));});await mkdir('artifacts/phase-20',{recursive:true});await page.screenshot({path:`artifacts/phase-20/${name}.png`,fullPage:true});}
for(const [width,height] of [[1440,900],[1366,768],[1194,834],[834,1194],[390,844],[320,740]])test(`catalogue geometry and localized tabs ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await draft(page,'design');
 for(const collection of ['WOVEN','PRINTED']){await page.getByRole('tab',{name:collection,exact:true}).click();const image=page.locator('.design-card img');await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(i=>{const r=i.getBoundingClientRect();return Math.abs(r.width-r.height)<1&&r.height<600;})).toBe(true);expect(await image.getAttribute('srcset')).toContain('.webp');await expect(page.locator('.design-card .image-button')).toHaveCSS('aspect-ratio','1 / 1');}
 await shot(page,`catalogue-${width}`);await page.getByRole('button',{name:'Cambiar a español'}).click();await expect(page.getByRole('tab',{name:'TEJIDOS',exact:true})).toBeVisible();await expect(page.getByRole('tab',{name:'ESTAMPADOS',exact:true})).toBeVisible();await expect(page.getByRole('tab',{name:/\//})).toHaveCount(0);
});
for(const font of [1,9,17,18,33])test(`real Font ${font}: modal, front/back, review, order, saved and production`,async({page})=>{
 await draft(page,'lettering',font,'Maximiliano Rodriguez');await page.getByRole('button',{name:'View all lettering styles →'}).click();await realFont(page,'.lettering-selected .fitted-lettering',font);if([9,17,18].includes(font))await shot(page,'modal-font-'+font);await page.keyboard.press('Escape');
 await draft(page,'personalization',font);await realFont(page,'.tag-face-name .fitted-lettering',font);await page.getByRole('button',{name:'View back',exact:true}).click();await expect(page.locator('.tag-detail-text').first()).toHaveCSS('font-family',/Montserrat/);
 await draft(page,'review',font);await realFont(page,'.collar-review-lettering .fitted-lettering',font);await expect(page.locator('.flow-title .eyebrow')).toHaveCount(0);if(font===33)await shot(page,'review-font-33');
 await draft(page,'order-summary',font,'Pipo',true);await realFont(page,'.collar-collapse-label .fitted-lettering',font);await shot(page,`order-font-${font}`);await page.getByRole('button',{name:'Save order'}).click();await realFont(page,'.collar-collapse-label .fitted-lettering',font);await expect(page.locator('.success-mark,.complete .notice')).toHaveCount(0);await expect(page.getByText('Local demo · not submitted')).toHaveCount(0);await expect(page.locator('.confirmation-collars .collar-collapse-toggle')).toHaveCount(2);await shot(page,`confirmation-font-${font}-two`);
 await page.goto('/#/production');await page.locator('summary').first().click();await realFont(page,'.item-card .fitted-lettering',font);await expect(page.locator('.detail-row dt').filter({hasText:'Extra text'})).toHaveCount(0);
});
for(const width of [1440,1366,1194,834,390,320])test(`structured summary and confirmation ${width}`,async({page})=>{
 await page.setViewportSize({width,height:844});await draft(page,'order-summary',9,'Pipo',true);await realFont(page,'.collar-collapse-label .fitted-lettering',9);
 await page.locator('.collar-collapse-toggle').first().click();await expect(page.locator('.order-collar-summary').first().getByText('Antonela Suarez',{exact:false})).toBeVisible();await expect(page.locator('.order-collar-summary').getByText('No personalization')).toHaveCount(0);await expect(page.locator('.order-collar-summary').getByText('Extra text')).toHaveCount(0);
 if(width<601){await expect(page.getByRole('heading',{name:'LETTERING & DESIGN',exact:true}).first()).toBeVisible();const image=await page.locator('.collar-collapse-thumb').first().boundingBox();expect(image!.width).toBeLessThanOrEqual(120);await expect(page.locator('.confirmation-detail-collar .summary-facts').first()).toBeVisible();}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width>800)expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBe(true);await shot(page,`order-${width}`);await page.getByRole('button',{name:'Save order'}).click();await realFont(page,'.collar-collapse-label .fitted-lettering',9);await page.locator('.confirmation-collars .collar-collapse-toggle').first().click();await shot(page,`confirmation-${width}`);
 await expect(page.locator('.confirmation-detail-collar .summary-facts').first()).toBeVisible();await expect(page.locator('.confirmation-decoration svg')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const actions=await page.locator('.downloads .button-row').boundingBox(),panel=await page.locator('.complete').boundingBox();expect(actions!.x).toBeGreaterThanOrEqual(panel!.x);expect(actions!.x+actions!.width).toBeLessThanOrEqual(panel!.x+panel!.width+1);
});
for(const [purpose,font,tag] of [['none',1,'anti_fall'],['decoration',9,'hanging'],['drawing',33,'hanging'],['dog_photo',1,'anti_fall']] as const)test(`exports and thumbnails: ${purpose}, Font ${font}`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await draft(page,'order-summary',font,'Maximiliano Rodriguez',true);
 await page.evaluate(async({purpose,tag})=>{const saved=JSON.parse(sessionStorage.getItem('colti-draft-v1')!);saved.current=saved.items[0];saved.current.personalization_type=purpose;saved.current.tag_type=tag;if(purpose!=='decoration')saved.current.decorationIcon=undefined;
  if(purpose==='drawing'||purpose==='dog_photo'){const path='/src/data/backend.ts';const {upload}=await import(path);const canvas=document.createElement('canvas');canvas.width=100;canvas.height=80;canvas.getContext('2d')!.fillRect(5,5,80,60);const blob=await new Promise<Blob>(resolve=>canvas.toBlob(b=>resolve(b!),'image/png'));saved.current.attachments=[await upload(new File([blob],purpose+'.png',{type:'image/png'}),saved,()=>{})];}
  sessionStorage.setItem('colti-draft-v1',JSON.stringify(saved));
 },{purpose,tag});await page.reload();await realFont(page,'.collar-collapse-label .fitted-lettering',font);
 if(purpose==='drawing'||purpose==='dog_photo'){await page.locator('.collar-collapse-toggle').first().click();await expect(page.locator('.attachment-thumbnail')).toBeVisible();await shot(page,`mobile-${purpose}`);}
 await page.getByRole('button',{name:'Save order'}).click();await expect(page.locator('.confirmation-collars .collar-collapse-toggle')).toHaveCount(2);
 const rendering=await page.evaluate(async()=>{const path='/src/exports/documents.ts';const {renderPages}=await import(path);const fonts:string[]=[],text:string[]=[];const original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(value,x,y,maxWidth){fonts.push(this.font);text.push(value);return maxWidth===undefined?original.call(this,value,x,y):original.call(this,value,x,y,maxWidth);};try{const saved=JSON.parse(sessionStorage.getItem('colti-demo-orders-v1')!)[0];await renderPages(saved,'en');return {fonts,text};}finally{CanvasRenderingContext2D.prototype.fillText=original;}});
 expect(rendering.fonts.some(f=>f.includes(`colti-font-${font}-`))).toBe(true);expect(rendering.fonts.some(f=>f.includes('colti-font-33-'))).toBe(true);expect(rendering.text.join(' ')).toContain('Maximiliano Rodriguez');expect(rendering.text.join(' ')).toContain('Antonela Suarez');expect(rendering.text.join(' ')).toContain('Quito');
 for(const format of ['PDF','JPG']){const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download '+format+' ↓'}).click();const file=await downloaded;await mkdir('artifacts/phase-20',{recursive:true});await file.saveAs(`artifacts/phase-20/${purpose}.${format.toLowerCase()}`);}
});
