import {createTestDatabase} from './local-postgres.mjs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const db=await createTestDatabase();let checks=0;
const equal=(a,b)=>{assert.deepEqual(a,b);checks++;};
const owner=randomUUID(),customer=randomUUID();
const row=async()=> (await db.query("select * from public.closures where key='plastic_buckle'")).rows[0];
async function asUser(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role);}
async function save(value){return (await db.query('select public.admin_closure($1::jsonb,$2) as c',[JSON.stringify(value),value.revision])).rows[0].c;}
async function available(size,width){return (await db.query("select public.closure_available('plastic_buckle',$1,$2) as ok",[size,width])).rows[0].ok;}
try{
 await db.query('insert into auth.users values ($1),($2)',[owner,customer]);await db.query('insert into public.production_owner values (true,$1)',[owner]);
 await asUser(customer);equal((await db.query('select count(*)::integer as n from public.closures')).rows[0].n,3);const denied=await row();await assert.rejects(()=>save(denied));checks++;
 await asUser(owner);let c=await row();
 for(const p of (await db.query('select * from public.size_widths')).rows)equal(await available(p.size_code,p.width_cm),true);
 equal(await available('M',3),false);
 await assert.rejects(()=>save({...c,preferences:{M:{enabled:true,widths:{3:true}}}}));checks++;
 c=await save({...c,name_en:'My buckle',name_es:'Mi hebilla',icon:'/icons/metal-buckle.svg',display_order:2,preferences:{XS:{enabled:true,widths:{1:false,'1.5':true}},M:{enabled:true,widths:{'2.5':false}}}});
 equal([c.name_en,c.name_es,c.icon,c.display_order],['My buckle','Mi hebilla','/icons/metal-buckle.svg',2]);equal(await available('XS',1),false);equal(await available('XS',1.5),true);equal(await available('M',2.5),true);
 c=await save({...c,preferences:{...c.preferences,XS:{...c.preferences.XS,enabled:false}}});equal(await available('XS',1.5),false);equal(c.preferences.XS.widths,{'1':false,'1.5':true});
 c=await save({...c,preferences:{...c.preferences,XS:{...c.preferences.XS,enabled:true}}});equal(await available('XS',1),false);equal(await available('XS',1.5),true);
 const item={id:randomUUID(),size_code:'XS',width_cm:1.5,design_id:'10000000-0000-4000-8000-000000000001',collar_type:'plastic_buckle',tag_type:'anti_fall',pet_name:'Luna',tag_phone:'+593 99 123 4567',extra_text:'',font_number:36,personalization_type:'none',personalization_notes:'',attachments:[]};
 const key=randomUUID(),draft=randomUUID(),args=[key,draft,JSON.stringify({name:'Closure test',phone:'+593 99 123 4567'}),JSON.stringify([item])];const confirm='select public.confirm_order($1,$2,$3::jsonb,$4::jsonb) as doc';
 await asUser(customer);const original=(await db.query(confirm,args)).rows[0].doc;equal(original.items[0].closure_snapshot.name_en,'My buckle');
 await asUser(owner);c=await save({...c,name_en:'Renamed buckle',icon:'/icons/martingale.svg',active:false});equal(await available('XS',1.5),false);equal(c.preferences.XS.widths,{'1':false,'1.5':true});
 await asUser(customer);equal((await db.query(confirm,args)).rows[0].doc,original);await assert.rejects(()=>db.query(confirm,[randomUUID(),...args.slice(1)]));checks++;
 equal((await db.query('select public.find_order($1) as doc',[key])).rows[0].doc.items[0].closure_snapshot,original.items[0].closure_snapshot);
 await asUser(owner);c=await save({...c,active:true});equal(await available('XS',1.5),true);await assert.rejects(()=>save({...c,revision:c.revision-1}));checks++;
 await asUser(customer);await assert.rejects(()=>save(c));checks++;await assert.rejects(()=>db.query("update public.closures set active=false"));checks++;
 await asUser(owner);
 const custom={...c,key:'custom_0123456789abcdef0123',revision:0,name_en:'New closure',name_es:'Nuevo cierre',active:false,preferences:{}};
 const create=async value=>(await db.query('select public.admin_create_closure($1::jsonb) as c',[JSON.stringify(value)])).rows[0].c;
 let created=await create(custom);equal(created.active,false);equal(created.revision,1);
 await assert.rejects(()=>create(custom));checks++;
 await assert.rejects(()=>create({...custom,key:'custom_1123456789abcdef0123',preferences:{M:{enabled:true,widths:{3:true}}}}));checks++;
 equal((await db.query("select count(*)::integer as n from public.closures where key='custom_1123456789abcdef0123'")).rows[0].n,0);
 const customArgs=[randomUUID(),randomUUID(),args[2],JSON.stringify([{...item,id:randomUUID(),collar_type:custom.key}])];
 await asUser(customer);await assert.rejects(()=>create({...custom,key:'custom_2123456789abcdef0123'}));checks++;await assert.rejects(()=>db.query(confirm,customArgs));checks++;
 await asUser(owner);created=await save({...created,active:true});
 await asUser(customer);const customOrder=(await db.query(confirm,customArgs)).rows[0].doc;equal(customOrder.items[0].collar_type,custom.key);equal(customOrder.items[0].closure_snapshot.name_es,'Nuevo cierre');
 await asUser(owner);await save({...created,active:false,name_en:'Updated closure'});
 await asUser(customer);equal((await db.query(confirm,customArgs)).rows[0].doc,customOrder);
 await asUser(owner);
 const tags=async()=>(await db.query('select value,revision from public.id_tag_configuration where id')).rows[0];
 let tc=await tags();const tagSave=async(value,revision)=>(await db.query('select public.admin_id_tags($1::jsonb,$2) as c',[JSON.stringify(value),revision])).rows[0].c;
 const tagResolve=async(size,width)=>(await db.query('select public.configured_tag_snapshot($1::jsonb) as s',[JSON.stringify({...item,size_code:size,width_cm:width,tag_type:'anti_fall'})])).rows[0].s;
 for(const m of tc.value.mapping)equal((await tagResolve(m.size,m.width)).model.key,m.model);
 equal(await tagResolve('M',3),null);
 await assert.rejects(()=>tagSave({...tc.value,mapping:[{size:'XS',width:1,model:'micro'}]},tc.revision));checks++;
 await assert.rejects(()=>tagSave({...tc.value,mapping:[{size:'M',width:3,model:'large'}]},tc.revision));checks++;
 const antiItem={...item,collar_type:'martingale',id:randomUUID(),tag_type:'anti_fall',size_code:'XS',width_cm:1};
 const antiArgs=[randomUUID(),randomUUID(),args[2],JSON.stringify([antiItem])];
 await asUser(customer);const antiOrder=(await db.query(confirm,antiArgs)).rows[0].doc;equal(antiOrder.items[0].tag_snapshot.model.key,'miniature');
 await assert.rejects(()=>tagSave(tc.value,tc.revision));checks++;
 await asUser(owner);
 let next=await tagSave({...tc.value,anti:tc.value.anti.map(m=>m.key==='miniature'?{...m,active:false,name_en:'Changed'}:m)},tc.revision);
 equal(await tagResolve('XS',1),null);equal((await tagResolve('2XS',1)).model.key,'micro');
 await asUser(customer);equal((await db.query(confirm,antiArgs)).rows[0].doc,antiOrder);
 await assert.rejects(()=>db.query(confirm,[randomUUID(),...antiArgs.slice(1)]));checks++;
 await asUser(owner);next=await tagSave({...next,anti:next.anti.map(m=>({...m,active:true}))},next.revision);
 const hanging={...item,id:randomUUID(),tag_type:'hanging',tagShape:'bone',tagSize:'miniature',tagWidthCm:2.3,tagHeightCm:2};
 const hangArgs=[randomUUID(),randomUUID(),args[2],JSON.stringify([hanging])];
 await asUser(customer);const hangOrder=(await db.query(confirm,hangArgs)).rows[0].doc;equal(hangOrder.items[0].tag_snapshot.size.id,'miniature');
 await asUser(owner);next=await tagSave({...next,hanging:next.hanging.map(m=>m.key==='bone'?{...m,sizes:m.sizes.map(z=>({...z,active:false}))}:m)},next.revision);
 await asUser(customer);await assert.rejects(()=>db.query(confirm,[randomUUID(),...hangArgs.slice(1)]));checks++;equal((await db.query(confirm,hangArgs)).rows[0].doc,hangOrder);
 await asUser(owner);next=await tagSave({...next,hanging:next.hanging.map(m=>m.key==='bone'?{...m,sizes:m.sizes.map(z=>({...z,active:true,width:2.4}))}:m)},next.revision);
 await asUser(customer);const modified=(await db.query(confirm,[randomUUID(),randomUUID(),args[2],JSON.stringify([{...hanging,id:randomUUID(),tagWidthCm:2.4}])])).rows[0].doc;equal(modified.items[0].tag_snapshot.width,2.4);equal((await db.query(confirm,hangArgs)).rows[0].doc,hangOrder);
 console.log(`PASS: ${checks} closure PostgreSQL checks — permissions, master pairs, preferences, names/icons/order, confirmation, conflict and immutable history.`);
}finally{await db.close();}
