import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createDriveOAuth,driveScope} from './drive-oauth-core.mjs';
import {encryptedDriveStore,createDriveMiddleware} from './drive-oauth-server.mjs';
import {createServer} from 'node:http';
function fixture(options={}){let saved=null,clock=1000000;const calls=[];const store={configured:true,read:async()=>saved,write:async v=>{saved=v;},clear:async()=>{saved=null;}};const oauth=createDriveOAuth({clientId:'test-client',clientSecret:'test-secret',redirectUri:'http://127.0.0.1:4174/api/admin/drive/callback',store,now:()=>clock,fetcher:async(url,init)=>{calls.push({url,body:Object.fromEntries(init.body)});return {ok:true,status:200,json:async()=>({access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,scope:driveScope})};},sync:async(target,token)=>calls.push({target,token}),...options});return {oauth,calls,store,getSaved:()=>saved,setClock:v=>{clock=v;}};}
async function connect(f){const start=f.oauth.connect('browser');const url=new URL(start.url);await f.oauth.callback({state:url.searchParams.get('state'),code:'test-code',browser:'browser'});return url;}
test('authorization uses read-only scope, offline access, PKCE and single-use browser state',async()=>{const f=fixture();const url=new URL(f.oauth.connect('browser').url),state=url.searchParams.get('state');assert.equal(url.searchParams.get('scope'),driveScope);assert.equal(url.searchParams.get('access_type'),'offline');assert.equal(url.searchParams.get('code_challenge_method'),'S256');await assert.rejects(f.oauth.callback({state,code:'code',browser:'other'}),/DriveStateInvalid/);await f.oauth.callback({state,code:'code',browser:'browser'});await assert.rejects(f.oauth.callback({state,code:'code',browser:'browser'}),/DriveStateInvalid/);assert(!JSON.stringify(await f.oauth.status()).includes('test-access'));assert.equal((await f.oauth.status()).connected,true);});
test('expired state, denied consent and missing Drive scope never connect',async()=>{const f=fixture();const state=new URL(f.oauth.connect('browser').url).searchParams.get('state');f.setClock(2000000);await assert.rejects(f.oauth.callback({state,code:'code',browser:'browser'}),/DriveStateInvalid/);const denied=new URL(f.oauth.connect('browser').url).searchParams.get('state');await assert.rejects(f.oauth.callback({state:denied,error:'access_denied',browser:'browser'}),/DriveConsentDenied/);const noScope=fixture({fetcher:async()=>({ok:true,json:async()=>({access_token:'a',refresh_token:'r',expires_in:3600,scope:'profile'})})});await assert.rejects(connect(noScope),/DriveScopeMissing/);assert.equal((await noScope.oauth.status()).connected,false);});
test('sync refreshes expired tokens and records success only after completion',async()=>{const f=fixture();await connect(f);f.setClock(5000000);await f.oauth.synchronize('catalog');assert.equal(f.calls[1].body.grant_type,'refresh_token');assert.equal(f.calls[2].target,'catalog');assert.equal((await f.oauth.status()).lastSync.catalog,new Date(5000000).toISOString());await f.oauth.disconnect();assert.equal((await f.oauth.status()).connected,false);await assert.rejects(f.oauth.synchronize('catalog'),/DriveNotConnected/);});
test('failed and overlapping syncs do not report successful updates',async()=>{let release;const f=fixture({sync:()=>new Promise((_,reject)=>{release=()=>reject(Error('DriveSyncFailed'));})});await connect(f);const running=f.oauth.synchronize('catalog');await new Promise(r=>setImmediate(r));await assert.rejects(f.oauth.synchronize('hero'),/DriveBusy/);await assert.rejects(f.oauth.disconnect(),/DriveBusy/);release();await assert.rejects(running,/DriveSyncFailed/);assert.equal((await f.oauth.status()).lastSync.catalog,null);});
test('tokens are encrypted on disk and disconnect removes the local grant',async()=>{const dir=await mkdtemp(join(tmpdir(),'colti-drive-test-'));try{const path=join(dir,'grant.json'),key=randomBytes(32).toString('base64'),store=encryptedDriveStore(path,key);await store.write({refresh_token:'test-private-token'});assert(!(await readFile(path,'utf8')).includes('test-private-token'));assert.deepEqual(await store.read(),{refresh_token:'test-private-token'});await assert.rejects(encryptedDriveStore(path,randomBytes(32).toString('base64')).read());await store.clear();assert.equal(await store.read(),null);}finally{await rm(dir,{recursive:true,force:true});}});
test('HTTP endpoints reject unauthenticated and cross-origin mutations',async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const middleware=createDriveMiddleware({root:process.cwd(),origin,env:{},authorize:async req=>req.headers.authorization==='Bearer owner'});server.on('request',(req,res)=>void middleware(req,res,()=>{res.writeHead(404);res.end();}));try{assert.equal((await fetch(origin+'/api/admin/drive/status')).status,403);const status=await fetch(origin+'/api/admin/drive/status',{headers:{Authorization:'Bearer owner'}});assert.deepEqual(await status.json(),{configured:false,connected:false,lastSync:{catalog:null,hero:null}});const denied=await fetch(origin+'/api/admin/drive/connect',{method:'POST',headers:{Authorization:'Bearer owner','Content-Type':'application/json',Origin:'https://other.example'},body:'{}'});assert.equal(denied.status,403);const missing=await fetch(origin+'/api/admin/drive/connect',{method:'POST',headers:{Authorization:'Bearer owner','Content-Type':'application/json',Origin:origin},body:'{}'});assert.equal((await missing.json()).error,'DriveNotConfigured');}finally{await new Promise(r=>server.close(r));}});
