import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createTestDatabase} from './local-postgres.mjs';
const db=await createTestDatabase();let checks=0;const equal=(a,b)=>{assert.deepEqual(a,b);checks++;};
try{
 const owner=randomUUID();await db.query('insert into auth.users values ($1)',[owner]);await db.query('insert into public.production_owner values(true,$1)',[owner]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec('set role authenticated');
 const design=(await db.query('select * from public.designs limit 1')).rows[0];await db.query('select public.admin_delete_design($1,$2)',[design.id,design.asset_version]);equal((await db.query("select public.catalog_variant_available($1,'M',2.5) available",[design.id])).rows[0].available,false);await assert.rejects(()=>db.query('select public.admin_delete_design($1,$2)',[design.id,design.asset_version]));checks++;
 const closure=(await db.query("select * from public.closures where key='plastic_buckle'")).rows[0];await db.query('select public.admin_delete_closure($1,$2)',[closure.key,closure.revision]);equal((await db.query("select public.closure_available('plastic_buckle','M',2.5) available")).rows[0].available,false);
 const row=(await db.query('select * from public.id_tag_configuration')).rows[0];let cfg={...row.value,revision:row.revision};const save=async c=>(await db.query('select public.admin_id_tags($1::jsonb,$2) value',[JSON.stringify(c),c.revision])).rows[0].value;
 const model={key:'custom_123456789abc',name_en:'New',name_es:'Nueva',icon:'/icons/tag-circle.svg',active:true,display_order:9,sizes:[{id:'small',name_en:'Small',name_es:'Pequeña',width:2,height:2,active:true}]};cfg=await save({...cfg,hanging:[...cfg.hanging,model]});equal(cfg.hanging.at(-1).name_en,'New');equal((await db.query("select width_cm from public.tag_options where shape=$1",[model.key])).rows[0].width_cm,'2');const currentDesign=(await db.query("select d.id from public.designs d join public.design_compatibility c on c.design_id=d.id where d.active and not d.deleted and c.size_code='XS' and c.width_cm=1.5 limit 1")).rows[0].id;
 const item={id:randomUUID(),size_code:'XS',width_cm:1.5,design_id:currentDesign,collar_type:'metal_buckle',tag_type:'hanging',tagShape:model.key,tagSize:'small',tagWidthCm:2,tagHeightCm:2,pet_name:'Test',tag_phone:'+593 999 000 001',extra_text:'',font_number:36,personalization_type:'none',personalization_notes:'',attachments:[]};
 const orderArgs=[randomUUID(),randomUUID(),JSON.stringify({name:'Local test',phone:'+593 999 000 001'}),JSON.stringify([item])];const confirm='select public.confirm_order($1,$2,$3::jsonb,$4::jsonb) doc';const original=(await db.query(confirm,orderArgs)).rows[0].doc;equal(original.items[0].tag_snapshot.model.key,model.key);
 cfg=await save({...cfg,hanging:cfg.hanging.map(m=>m.key===model.key?{...m,active:false,deleted:true}:m)});equal(cfg.hanging.at(-1).deleted,true);equal((await db.query(confirm,orderArgs)).rows[0].doc,original);await assert.rejects(()=>db.query(confirm,[randomUUID(),...orderArgs.slice(1)]));checks++;await assert.rejects(()=>save({...cfg,hanging:cfg.hanging.filter(m=>m.key!==model.key)}));checks++;await assert.rejects(()=>save({...cfg,hanging:cfg.hanging.map(m=>m.key===model.key?{...m,active:true,deleted:false}:m)}));checks++;
 await db.exec('reset role');await db.query('update public.designs set active=true where id=$1',[design.id]);equal((await db.query('select active,deleted from public.designs where id=$1',[design.id])).rows[0],{active:false,deleted:true});
 console.log('PASS: '+checks+' inventory CRUD PostgreSQL checks');
}finally{await db.close();}

