import {useEffect,useState} from 'react';
import {collections,type CollectionRecord} from '../data/collectionsBackend';
import {categoryLabel} from '../domain/catalogGroups';
import {ConfirmDelete} from './ConfirmDelete';
export function Collections({onChange}:{onChange:()=>void}){
 const [rows,setRows]=useState<CollectionRecord[]>([]),[name,setName]=useState(''),[editing,setEditing]=useState<CollectionRecord|null>(null),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rowError,setRowError]=useState(''),[removing,setRemoving]=useState<CollectionRecord|null>(null);
 const load=()=>collections.load().then(setRows);useEffect(()=>{void load().catch(()=>setError('Could not load collections.'));},[]);
 async function run(work:()=>Promise<void>,kind:'create'|'row'|'delete'){if(busy)return;setBusy(true);setError('');setRowError('');try{await work();await load();onChange();if(kind==='create')setName('');if(kind==='row')setEditing(null);if(kind==='delete')setRemoving(null);}catch{const message='Could not save. The name may already exist or this collection changed in another session.';if(kind==='row'&&editing)setRowError(message);else setError(message);}finally{setBusy(false);}}
 return <section className="admin-collections"><form className="admin-category-create" onSubmit={e=>{e.preventDefault();void run(()=>collections.create(name),'create');}}><label>New collection<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="For example, Florales"/></label><button className="admin-primary" disabled={busy||!name.trim()}>Create collection</button></form>{error&&!removing&&<p role="alert" className="admin-error">{error}</p>}<div className="admin-collection-list">{rows.map(c=><article key={c.name}>{editing?.name===c.name?<form className="admin-inline-rename" onSubmit={e=>{e.preventDefault();void run(()=>collections.change('rename',c.name,draft,c.revision),'row');}}><label>Collection name<input autoFocus required maxLength={80} value={draft} disabled={busy} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Escape'&&!busy){setEditing(null);setRowError('');}}}/></label><div className="admin-controls"><button type="button" disabled={busy} onClick={()=>{setEditing(null);setRowError('');}}>Cancel</button><button disabled={busy||!draft.trim()||draft.trim()===c.name}>Save</button></div>{rowError&&<p role="alert" className="admin-error">{rowError}</p>}</form>:<><div><strong>{categoryLabel(c.name)}</strong><span>{c.active?'Active':'Inactive'}</span></div>{c.name.toLocaleLowerCase('es')!=='sin colección'&&<div className="admin-controls"><button disabled={busy} onClick={()=>{setEditing(c);setDraft(categoryLabel(c.name));setRowError('');}}>Edit</button><button disabled={busy} onClick={()=>void run(()=>collections.change(c.active?'deactivate':'activate',c.name,null,c.revision),'row')}>{c.active?'Deactivate':'Activate'}</button><button disabled={busy} onClick={()=>{setRemoving(c);setError('');}}>Delete</button></div>}</>}</article>)}</div>{removing&&<ConfirmDelete name={categoryLabel(removing.name)} description="Its designs will move to Sin colección. Existing orders keep their original details." busy={busy} error={error} cancel={()=>{setRemoving(null);setError('');}} confirm={()=>void run(()=>collections.change('delete',removing.name,null,removing.revision),'delete')}/>}</section>;
}
