import {useEffect,useState,useRef,type ReactNode} from 'react';
import {driveConnection} from '../data/adminBackend';
import type {DriveConnectionStatus,DriveSyncTarget} from '../application/driveConnection';
const messages:Record<string,string>={DriveNotConfigured:'Falta configurar la conexión de Google de COLTI en el servidor.',DriveServerUnavailable:'La conexión de Drive aún no está instalada en este servidor.',DriveNotConnected:'Conecta Google Drive antes de sincronizar.',DriveReconnect:'La autorización venció. Vuelve a conectar Google Drive.',DriveBusy:'Ya hay una sincronización en curso. Espera a que termine.',DriveSyncFailed:'No se completó la sincronización. Revisa la conexión y reintenta.',Unauthorized:'Tu cuenta no tiene acceso administrativo.',DriveConsentDenied:'No se autorizó el acceso. Puedes volver a conectar.',DriveScopeMissing:'Google no concedió el permiso de lectura necesario.',DriveStateInvalid:'La autorización expiró. Vuelve a conectar.'};
export function DriveConnection({target,compact=false,ordersSync:_ordersSync=false,onSynced,children}:{target:DriveSyncTarget;compact?:boolean;ordersSync?:boolean;onSynced?:()=>Promise<void>;children?:ReactNode}){
 const [status,setStatus]=useState<DriveConnectionStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState('');
 const actionLock=useRef(false);
 const [expanded,setExpanded]=useState(false),[syncing,setSyncing]=useState(false);
 const describe=(e:unknown)=>messages[e instanceof Error?e.message:'']||messages.DriveSyncFailed;
 async function load(){try{const next=await driveConnection.status();setStatus(next);setError(next.automatic?.targets[target].issue?messages[next.automatic.targets[target].issue!]||messages.DriveSyncFailed:'');}catch(e){setError(describe(e));}}
 useEffect(()=>{void load();const params=new URLSearchParams(location.search);if(params.get('drive')==='connected')setFeedback('Google Drive conectado. Ya puedes sincronizar.');else if(params.has('drive_error'))setError(messages[params.get('drive_error')!]||messages.DriveSyncFailed);if(params.has('drive')||params.has('drive_error')){params.delete('drive');params.delete('drive_error');history.replaceState(null,'',location.pathname+(params.size?'?'+params:''));}},[]);
 async function action(work:()=>Promise<void>){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');setFeedback('');try{await work();}catch(e){setError(describe(e));setFeedback('');}finally{actionLock.current=false;setBusy(false);}}
 if(compact){return <section className="admin-drive-import" aria-label="Google Drive import"><button className="admin-drive-import-toggle" aria-expanded={expanded} aria-controls={target+'-drive-actions'} onClick={()=>setExpanded(v=>!v)}><svg className="admin-drive-symbol" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M9 3h6l7 12-3 6H5l-3-6L9 3Z M9 3l7 12H2 M15 3 5 21 M16 15h6" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg><span>Import from Google Drive</span><span aria-hidden="true">{expanded?'▴':'▾'}</span></button>{expanded&&<div id={target+'-drive-actions'} className="admin-drive-import-body"><div><strong>Google Drive</strong><p>{status?.connected?'Connected · Manual import':'Connect to import your photos in bulk.'}</p></div><div className="admin-controls"><button disabled={busy||syncing||!status?.connected} onClick={()=>action(async()=>{setSyncing(true);try{await driveConnection.sync(target);await load();await onSynced?.();setFeedback('Import completed.');}finally{setSyncing(false);}})}>{syncing?'Importing…':'Import images'}</button><button disabled={busy||!status?.configured} onClick={()=>action(async()=>{const {url}=await driveConnection.connect();if(new URL(url).origin!=='https://accounts.google.com')throw Error('DriveSyncFailed');location.assign(url);})}>{status?.connected?'Reconnect':'Connect'}</button>{status?.connected&&<button disabled={busy} onClick={()=>action(async()=>{await driveConnection.disconnect();await load();setFeedback('Disconnected. Existing images are preserved.');})}>Disconnect</button>}</div>{feedback&&<p className="admin-feedback" role="status">{feedback}</p>}{children}{error&&<p className="admin-error" role="alert">{error}</p>}</div>}</section>;}

 return <section className={'admin-drive-panel'+(compact?' admin-drive-taskbar':'')} aria-label="Conexión Google Drive"><div><h2>Google Drive</h2>{compact?<p>{status?.connected?'Connected · Manual sync':'Connect Google Drive'}{status?.lastSync[target]&&<> · Last sync {new Date(status.lastSync[target]!).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</>}</p>:<><p>{status?.connected?'Conectado · acceso de lectura':'Conecta tu cuenta para actualizar las imágenes desde tus carpetas.'}</p>{status?.lastSync[target]&&<p>Última sincronización: {new Date(status.lastSync[target]!).toLocaleString()}</p>}</>}</div><div className="admin-controls">{compact&&<details className="admin-drive-options"><summary>Connection</summary><div className="admin-controls"><button disabled={busy||!status?.configured} onClick={()=>action(async()=>{const {url}=await driveConnection.connect();const parsed=new URL(url);if(parsed.origin!=='https://accounts.google.com')throw new Error('DriveSyncFailed');location.assign(url);})}>{status?.connected?'Volver a conectar':'Conectar Google Drive'}</button>{status?.connected&&<button disabled={busy} onClick={()=>action(async()=>{await driveConnection.disconnect();await load();setFeedback('Google Drive desconectado. Las imágenes actuales se conservan.');})}>Desconectar</button>}</div></details>}{!compact&&<button disabled={busy||!status?.configured} onClick={()=>action(async()=>{const {url}=await driveConnection.connect();const parsed=new URL(url);if(parsed.origin!=='https://accounts.google.com')throw new Error('DriveSyncFailed');location.assign(url);})}>{status?.connected?'Volver a conectar':'Conectar Google Drive'}</button>}<button className={compact?'admin-drive-sync-action':'admin-primary'} disabled={busy||!status?.connected} onClick={()=>action(async()=>{setFeedback('Sincronizando… Puede tardar unos minutos.');await driveConnection.sync(target);await load();setFeedback('Sincronización completada.');})}>{busy?(compact?'Syncing…':'Espera…'):compact?'Sync hero':target==='catalog'?'Sincronizar catálogo':'Sincronizar hero'}</button>{!compact&&status?.connected&&<button disabled={busy} onClick={()=>action(async()=>{await driveConnection.disconnect();await load();setFeedback('Google Drive desconectado. Las imágenes actuales se conservan.');})}>Desconectar</button>}</div>{children}{status&&!status.configured&&<p className="admin-hint">Falta configurar la conexión de Google de COLTI en el servidor.</p>}{error&&<p className="admin-error" role="alert">{error}</p>}<p className="admin-feedback" role="status">{feedback}</p></section>;
}
