import {ConfirmDelete} from './ConfirmDelete';
import {Uploads} from './Uploads';
import {useState,useRef} from 'react';
import {admin} from '../data/adminBackend';
import {useSync} from '../ui/useSync';
import type {HeroConfiguration,HeroImage} from '../domain/admin';
import {mergeHeroSource,positionHero,toggleHero} from '../domain/heroEditing';
import {DriveConnection} from './DriveConnection';

export function Hero(){
 const [uploading,setUploading]=useState(false),[removing,setRemoving]=useState<HeroImage|null>(null);
 const [source,setSource]=useState<HeroImage[]>([]),[configuration,setConfiguration]=useState<HeroConfiguration|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[dragged,setDragged]=useState<string|null>(null),[over,setOver]=useState<string|null>(null);
 const preserve=useRef(false);preserve.current=dirty||busy;
 async function load(){try{const data=await admin.hero();setSource(data.source);setConfiguration(previous=>preserve.current&&previous?mergeHeroSource(previous,data.source):mergeHeroSource(data.configuration,data.source));setError('');}catch(e){setError('Could not load hero images. The current collection is preserved.');throw e;}}
 const sync=useSync('hero',load);
 const active=configuration?.images.filter(i=>i.active&&!i.deleted)||[],inactive=configuration?.images.filter(i=>!i.active&&!i.deleted)||[];
 function edit(work:(value:HeroConfiguration)=>HeroConfiguration){if(busy)return;setConfiguration(value=>value&&work(value));setDirty(true);setFeedback('');}
 async function save(){if(!configuration||busy||!dirty)return;setBusy(true);setError('');try{setConfiguration(await admin.saveHero(configuration));setDirty(false);setFeedback('Saved');}catch{setError('Could not save. Your changes are preserved. The configuration may have changed in another session; reload the saved version before trying again.');}finally{setBusy(false);}}
 async function remove(){if(!configuration||!removing||busy)return;setBusy(true);setError('');try{const next={...configuration,images:configuration.images.map(i=>i.id===removing.id?{...i,active:false,deleted:true}:i)};setConfiguration(await admin.saveHero(next));setDirty(false);setRemoving(null);setFeedback('Photo deleted');}catch{setError('Could not delete. Please retry.');}finally{setBusy(false);}}
 function card(image:HeroConfiguration['images'][number],position:number){const asset=source.find(s=>s.id===image.id);if(!asset)return null;const file=(asset.variants[1]||asset.variants[0]).file;
 return <article key={image.id} className={(!image.active?'is-inactive ':'')+(over===image.id?'hero-drop-target':'')} draggable={image.active&&!busy} onDragStart={e=>{setDragged(image.id);e.dataTransfer.setData('text/plain',image.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{setDragged(null);setOver(null);}} onDragOver={e=>{if(dragged&&image.active&&!busy){e.preventDefault();setOver(image.id);}}} onDragLeave={()=>setOver(null)} onDrop={e=>{e.preventDefault();if(dragged&&e.dataTransfer.getData('text/plain')===dragged)edit(c=>positionHero(c,dragged,position));setDragged(null);setOver(null);}}>
  <div className="admin-hero-image"><img src={/^https?:/.test(file)?file:import.meta.env.BASE_URL+file} alt={asset.name} width="240" height="320" loading="lazy"/>{image.active&&<span className="admin-position">{String(position+1).padStart(2,'0')}</span>}<span className={'admin-image-label '+(!image.active?'is-off':'')}>{image.active?'Active':'Inactive'}</span></div>
  <div className="admin-hero-body"><div className="admin-hero-card-title"><h2 title={asset.name}>{asset.name}</h2><button className="admin-hero-delete" disabled={busy} onClick={()=>{setRemoving(asset);setError('');}}>Delete</button></div><label className="admin-toggle"><span>{image.active?'On the website':'Hidden'}</span><input type="checkbox" aria-label={'Activate '+asset.name} disabled={busy} checked={image.active} onChange={()=>edit(c=>toggleHero(c,image.id))}/><span className="admin-toggle-track" aria-hidden="true"/></label>
   {image.active&&<div className="admin-hero-position-controls"><label>Position<select aria-label={'Position of '+asset.name} value={position} disabled={busy} onChange={e=>edit(c=>positionHero(c,image.id,Number(e.target.value)))}>{active.map((_,n)=><option key={n} value={n}>{n+1}</option>)}</select></label><button disabled={busy||position===0} onClick={()=>edit(c=>positionHero(c,image.id,0))} aria-label={'Move '+asset.name+' first'}>First</button><button disabled={busy||position===active.length-1} onClick={()=>edit(c=>positionHero(c,image.id,active.length-1))} aria-label={'Move '+asset.name+' last'}>Last</button></div>}
  </div></article>;
 }
 return <>{removing&&<ConfirmDelete name={removing.name} description="This photo will leave Hero and the website." busy={busy} error={error} cancel={()=>setRemoving(null)} confirm={()=>void remove()}/>}<div className="admin-page-heading"><h1>Hero images</h1><p>Choose your photos and the order they appear. New Drive photos arrive hidden until you activate them.</p></div><div className="admin-view-tabs admin-task-tabs" role="tablist" aria-label="Hero tasks"><button role="tab" aria-selected={!uploading} className={!uploading?'is-selected':''} onClick={()=>setUploading(false)}>Images</button><button role="tab" aria-selected={uploading} className={uploading?'is-selected':''} onClick={()=>setUploading(true)}>Add new</button></div>{uploading&&<DriveConnection target="hero" compact ordersSync onSynced={load}/>}<div hidden={!uploading} role="tabpanel" aria-label="Add new"><Uploads destination="hero" onUploaded={()=>{setUploading(false);setFeedback('Photo uploaded · ready to activate');void load().catch(()=>{});}}/></div><div hidden={uploading} role="tabpanel" aria-label="Images"><div className="admin-hero-savebar admin-publish-bar">
  <div className="admin-hero-toolbar"><div className="admin-hero-save-context"><strong>Image order & visibility</strong><p className="admin-feedback" role="status">{busy?'Saving…':dirty?'Unsaved changes':sync==='issue'?'Sync issue':feedback||'Saved'}</p></div><div className="admin-controls">{dirty&&<button disabled={busy} onClick={()=>{preserve.current=false;setDirty(false);void load().catch(()=>{});}}>Discard changes</button>}<button className="admin-primary" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'Saving…':'Save changes'}</button></div></div></div>{error&&<p className="admin-error" role="alert">{error}</p>}
  {!configuration?<p role="status">Loading images…</p>:<>{[{name:'ACTIVE',images:active},{name:'INACTIVE',images:inactive}].map(section=><section className="admin-hero-section" key={section.name} aria-label={section.name+' hero photos'}><div className="admin-section-heading"><h2>{section.name} <span>({section.images.length})</span></h2><p>{section.name==='ACTIVE'?'Shown in this order':'Hidden from the website'}</p></div><div className="admin-hero">{section.images.map(card)}</div>{!section.images.length&&<p className="admin-empty">No photos in this section.</p>}</section>)}</>}
 </div></>;
}
