import {useEffect,useState,useRef} from 'react';
import {loadCatalog} from '../data/backend';
import type {FontRecord} from '../domain/model';
import {generateFontCatalog} from '../exports/fontCatalog';
import {SnapshotLettering} from './SnapshotLettering';
import {lettering} from '../data/letteringBackend';
import {normalizeLettering,validateFontFile,type LetteringCatalog} from '../domain/lettering';
import {useSync} from '../ui/useSync';
import {ConfirmDelete} from './ConfirmDelete';
function FontCatalogDownload(){
 const [open,setOpen]=useState(false),[name,setName]=useState('PUPI'),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 async function generate(){setBusy(true);setError('');try{const current=await loadCatalog();const blob=await generateFontCatalog(current.fonts,name.trim());const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='COLTI-Lettering-Styles-'+name.trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40)+'.jpg';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Could not generate catalog.');}finally{setBusy(false);}}
 return <div className="font-catalog-action"><button disabled={busy} onClick={()=>{setOpen(true);setError('');}}>Generate font catalog</button>{open&&<dialog ref={dialog} className="admin-cancel-dialog" aria-label="Generate font catalog" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}><h2>Generate font catalog</h2><label>Preview name<input value={name} disabled={busy} maxLength={60} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="admin-error" role="alert">{error}</p>}<div className="admin-controls"><button disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="admin-primary" disabled={busy||!name.trim()} onClick={()=>void generate()}>{busy?'Generating…':'Generate JPG'}</button></div></dialog>}</div>;
}

export function Lettering(){
 const [saved,setSaved]=useState<LetteringCatalog|null>(null),[draft,setDraft]=useState<LetteringCatalog|null>(null),[editing,setEditing]=useState<FontRecord|null>(null),[removing,setRemoving]=useState<FontRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[over,setOver]=useState('');
 const pendingFile=useRef<File|null>(null);const files=useRef(new Map<string,File>()),drag=useRef(''),lock=useRef(false),urls=useRef<string[]>([]);
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(saved);
 useEffect(()=>()=>urls.current.forEach(URL.revokeObjectURL),[]);
 useSync('catalog',async()=>{if(lock.current)return;const value=await lettering.load();setSaved(previous=>JSON.stringify(previous)===JSON.stringify(value)?previous:value);if(!dirty&&!editing)setDraft(previous=>JSON.stringify(previous)===JSON.stringify(value)?previous:value);});
 function change(font:FontRecord){setDraft(c=>c?{...c,fonts:normalizeLettering(c.fonts.some(f=>f.id===font.id)?c.fonts.map(f=>f.id===font.id?font:f):[...c.fonts,font])}:c);}
 function move(id:string,position:number){setDraft(c=>{if(!c)return c;const list=[...c.fonts],index=list.findIndex(f=>f.id===id);if(index<0)return c;const [font]=list.splice(index,1);list.splice(position,0,font);return {...c,fonts:normalizeLettering(list)};});}
 async function save(){if(!draft||lock.current)return;lock.current=true;setBusy(true);setError('');try{const value=await lettering.save(draft,files.current);setSaved(value);setDraft(value);files.current.clear();setEditing(null);}catch(e){setError((e as Error).message||'Could not save. Your draft is preserved.');}finally{lock.current=false;setBusy(false);}}
 async function pick(file:File){if(!editing)return;setBusy(true);setError('');try{const valid=await validateFontFile(file);if(draft?.fonts.some(f=>f.id!==editing.id&&f.asset_hash===valid.hash&&!f.deleted))throw Error('This font is already in the catalog.');const url=URL.createObjectURL(file);urls.current.push(url);pendingFile.current=file;setEditing(current=>current?{...current,asset_path:url,asset_hash:valid.hash,asset_version:valid.hash,state:'ready',css_family:'colti-'+current.id}:current);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function discard(){files.current.clear();setDraft(saved?structuredClone(saved):null);setEditing(null);setError('');}
 return <section><div className="admin-section-heading"><h2>Lettering</h2><div className="lettering-heading-actions"><FontCatalogDownload/><button className="admin-primary" disabled={!draft||busy} onClick={()=>setEditing({id:crypto.randomUUID(),number:Math.max(0,...(draft?.fonts.map(f=>f.number)||[]))+1,label:'',state:'placeholder',asset_path:null,css_family:null,asset_version:'draft',active:false})}>+ Add font</button></div></div>
 <p className="admin-hint">Drag a card to reorder. Changes appear in Store after saving.</p>{error&&!editing&&<p role="alert" className="admin-error">{error}</p>}
 <div className="admin-lettering-list managed-lettering">{draft?.fonts.filter(f=>!f.deleted).map((f,index)=><article key={f.id} draggable={!busy} className={over===f.id?'font-drop-target':''} onDragStart={e=>{if((e.target as HTMLElement).closest('button,select')){e.preventDefault();return;}drag.current=f.id!;e.dataTransfer.effectAllowed='move';}} onDragOver={e=>{e.preventDefault();setOver(f.id!);}} onDragLeave={()=>setOver('')} onDrop={e=>{e.preventDefault();move(drag.current,index);setOver('');}} onDragEnd={()=>setOver('')}><div className="managed-font-preview" style={{['--lettering-max-size' as string]:`${f.presentation?.size||42}px`}}><small>{f.active?String(f.display_position??index+1).padStart(2,'0'):'—'}</small><SnapshotLettering font={f} name="Pupi" maximum={f.presentation?.size||42}/></div><footer><span className={'managed-font-status '+(f.active?'is-active':'is-inactive')}>{f.active?'Active':'Inactive'}</span><button onClick={()=>{pendingFile.current=null;setEditing({...f});}}>Edit</button><button onClick={()=>setRemoving(f)}>Delete</button></footer></article>)}</div>
 <div className="admin-controls lettering-save"><small>{dirty?'Unsaved changes':`${draft?.fonts.filter(f=>f.active&&!f.deleted).length||0} active styles · Current Store catalog`}</small><button disabled={!dirty||busy} onClick={discard}>Discard changes</button><button className="admin-primary" disabled={!dirty||busy} onClick={()=>void save()}>{busy?'Saving…':'Save changes'}</button></div>

 {editing&&<dialog className="admin-cancel-dialog managed-font-dialog" aria-label="Font configuration" ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={e=>{e.preventDefault();if(!busy){pendingFile.current=null;setEditing(null);}}}><h2>Font configuration</h2><label>Font file<input type="file" accept=".woff,.woff2" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void pick(f);}}/></label><p className="admin-hint">WOFF2 or WOFF · Up to 10 MB</p>{editing.state==='ready'&&<div className="managed-font-editor-preview" style={{['--lettering-max-size' as string]:`${editing.presentation?.size||42}px`}}><SnapshotLettering font={editing} name="Pupi" maximum={editing.presentation?.size||42}/></div>}<div className="managed-font-settings"><label htmlFor="managed-letter-size">Letter size <output>{editing.presentation?.size||42} px</output><input id="managed-letter-size" type="range" min="18" max="72" value={editing.presentation?.size||42} onChange={e=>setEditing({...editing,presentation:{...editing.presentation,size:Number(e.target.value)}})}/></label><label>Letter case<select value={editing.presentation?.transform||'none'} onChange={e=>setEditing({...editing,presentation:{...editing.presentation,transform:e.target.value}})}><option value="none">Normal</option><option value="uppercase">Uppercase</option>{editing.presentation?.transform==='channel'&&<option value="channel">Original ornamental style</option>}</select></label></div><label>Move to position<select value={editing.display_order??(draft?.fonts.length||0)+1} onChange={e=>setEditing({...editing,display_order:Number(e.target.value)})}>{Array.from({length:(draft?.fonts.filter(f=>!f.deleted).length||0)+(draft?.fonts.some(f=>f.id===editing.id)?0:1)},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label>Admin name<input value={editing.label} maxLength={200} onChange={e=>setEditing({...editing,label:e.target.value})}/></label><label><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Active in Store</label>{error&&<p role="alert" className="admin-error">{error}</p>}<div className="admin-controls"><button disabled={busy} onClick={()=>{pendingFile.current=null;setEditing(null);}}>Cancel</button><button className="admin-primary" disabled={busy||!editing.label.trim()||editing.state!=='ready'} onClick={()=>{if(pendingFile.current)files.current.set(editing.id!,pendingFile.current);pendingFile.current=null;change(editing);if(editing.display_order)move(editing.id!,editing.display_order-1);setEditing(null);setError('');}}>Apply to draft</button></div></dialog>}
 {removing&&<ConfirmDelete name={'lettering style “'+removing.label+'”'} description="It will be removed after Save changes. Existing orders keep their original font." busy={busy} cancel={()=>setRemoving(null)} confirm={()=>{change({...removing,active:false,deleted:true});setRemoving(null);}}/>}
 </section>;
}
