import {orderDate} from './orderDate';
import {useSync} from '../ui/useSync';
import {useEffect,useState,useRef} from 'react';
import {admin} from '../data/adminBackend';
import {nextStatuses,productionStatuses,productionStatus,statusLabel,type ProductionStatus} from '../domain/admin';
import type {Order} from '../domain/model';
import {DesignImage} from '../components';
import {CancelOrder} from './CancelOrder';
import {OrderDetail} from './OrderDetail';
const active:ProductionStatus[]=['new','in_progress','ready','delivered'];
const historic:ProductionStatus[]=['delivered','cancelled'];
const initialPages=()=>Object.fromEntries(productionStatuses.map(s=>[s,0])) as Record<ProductionStatus,number>;
const initialGroups=():Record<ProductionStatus,Order[]>=>({new:[],in_progress:[],ready:[],delivered:[],cancelled:[]});
function dates(from:string,to:string){const end=to?new Date(to+'T00:00:00'):null;end?.setDate(end.getDate()+1);return {...(from?{from:new Date(from+'T00:00:00').toISOString()}:{}),...(end?{to:end.toISOString()}:{})};}
export function OrdersBoard(){
 const [search,setSearch]=useState(''),[status,setStatus]=useState<ProductionStatus|''>(''),[view,setView]=useState<'board'|'history'>('board'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[groups,setGroups]=useState(initialGroups),[pages,setPages]=useState(initialPages),[more,setMore]=useState<Partial<Record<ProductionStatus,boolean>>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[moving,setMoving]=useState(false),[dragged,setDragged]=useState<Order|null>(null),[cancel,setCancel]=useState<Order|null>(null),[feedback,setFeedback]=useState(''),[opened,setOpened]=useState<string|null>(null);
 const [deliveredTotal,setDeliveredTotal]=useState(0);
 const [lastUpdated,setLastUpdated]=useState<Date|null>(null);
 const weekly=view==='board'&&!status;
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(opened)dialog.current?.showModal();},[opened]);
 const columns=(view==='history'?historic:active).filter(s=>!status||s===status);
 const syncState=useSync('orders',async()=>{await admin.list('', 'new',0);setRefresh(n=>n+1);});
 useEffect(()=>{let live=true;if(from&&to&&from>to){setError('Choose an end date on or after the start date.');setLoading(false);return;}setLoading(true);const timer=setTimeout(async()=>{try{const result=await Promise.all(columns.map(async s=>{if(weekly&&s==='delivered'){const result=await admin.deliveredWeek(search,dates(from,to));return {status:s,orders:result.orders,more:false,total:result.total};}const batches=await Promise.all(Array.from({length:pages[s]+1},(_,p)=>admin.list(search,s,p,dates(from,to))));return {status:s,orders:batches.flat(),more:batches.at(-1)!.length===20};}));if(live){setDeliveredTotal(result.find(r=>r.status==='delivered'&&'total' in r)?.total??0);setGroups(Object.assign(initialGroups(),...result.map(r=>({[r.status]:r.orders}))));setMore(Object.assign({},...result.map(r=>({[r.status]:r.more}))));setError('');setLastUpdated(new Date());}}catch{if(live)setError('Could not load orders. Please refresh and retry.');}finally{if(live)setLoading(false);}},200);return()=>{live=false;clearTimeout(timer);};},[search,status,view,from,to,pages,refresh]);
 function reset(){setPages(initialPages());}
 async function move(order:Order,next:ProductionStatus,reason=''){
  if(moving||!nextStatuses(order.status).includes(next))return;
  if(next==='cancelled'&&!cancel){setCancel(order);setError('');return;}
  setMoving(true);setError('');try{const result=await admin.status(order,next,reason);setGroups(g=>({...g,[productionStatus(order.status)]:g[productionStatus(order.status)].filter(o=>o.id!==order.id),[next]:[result.order,...g[next].filter(o=>o.id!==order.id)]}));setFeedback(order.order_code+' → '+statusLabel[next]);setCancel(null);setRefresh(n=>n+1);}catch{setError('Could not change the status. The order may have changed; refresh and retry.');}finally{setMoving(false);setDragged(null);}
 }
 const renderLane=(s:ProductionStatus)=><section key={s} className={'admin-board-column column-'+s+(dragged&&nextStatuses(dragged.status).includes(s)?' can-drop':'')} aria-label={statusLabel[s]+' orders'} onDragOver={e=>{if(dragged&&!moving&&nextStatuses(dragged.status).includes(s)){e.preventDefault();e.dataTransfer.dropEffect='move';}}} onDrop={e=>{e.preventDefault();if(dragged&&!moving&&e.dataTransfer.getData('text/plain')===dragged.id)void move(dragged,s);}}>
   <div className="admin-column-heading"><h2>{weekly&&s==='delivered'?'Delivered this week':statusLabel[s]}</h2><span>{weekly&&s==='delivered'?deliveredTotal:groups[s].length}{more[s]?'+':''}</span></div><div className="admin-column-cards">{groups[s].map(o=><article className="admin-ticket admin-compact-ticket" key={o.id} draggable={view==='board'&&!moving&&nextStatuses(o.status).length>0} onDragStart={e=>{setDragged(o);e.dataTransfer.setData('text/plain',o.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragged(null)}>
   <span className="admin-order-code">{o.order_code}</span><div className={"admin-compact-content collar-visual-"+(o.items.length>=4?"compact":o.items.length)}><div className="admin-ticket-images">{o.items.slice(0,o.items.length>4?3:4).map(i=><DesignImage key={i.id} design={i.design} locale="en"/>)}{o.items.length>4&&<span className="admin-more-images">+{o.items.length-3}</span>}</div><div><h3 title={o.items.map(i=>i.pet_name).join(' · ')}>{o.items.slice(0,2).map(i=>i.pet_name).join(' · ')}{o.items.length>2?' +'+(o.items.length-2):''}</h3><p title={o.customer_snapshot.name}>{o.customer_snapshot.name}</p><p>{o.items.length} {o.items.length===1?'collar':'collars'}</p><time dateTime={o.confirmed_at}>{orderDate(o.confirmed_at)}</time></div></div>
   <div className="admin-ticket-actions"><button className="admin-view-order" onClick={()=>setOpened(o.id)} aria-label={'Open order '+o.order_code}>View order</button>{nextStatuses(o.status).length>0&&<select aria-label={'Move '+o.order_code} value="" disabled={moving} onChange={e=>void move(o,e.target.value as ProductionStatus)}><option value="">Move…</option>{nextStatuses(o.status).map(n=><option key={n} value={n}>{statusLabel[n]}</option>)}</select>}</div>
   </article>)}</div>{weekly&&s==='delivered'&&deliveredTotal>6&&<button className="admin-load-more" onClick={()=>{setView('history');setStatus('delivered');reset();}}>View all delivered ({deliveredTotal})</button>}{more[s]&&<button className="admin-load-more" disabled={loading||moving} onClick={()=>setPages(p=>({...p,[s]:p[s]+1}))}>Load more {statusLabel[s].toLowerCase()}</button>}</section>;
 return <><div className="admin-page-heading"><h1>Orders</h1><p>Follow each order from its first little details to delivery.</p></div>
  <div className="admin-view-tabs" role="group" aria-label="Order view">{[{label:'All',value:''},{label:'New',value:'new'},{label:'In progress',value:'in_progress'},{label:'Ready',value:'ready'},{label:'History',value:'history'}].map(tab=>{const selected=tab.value==='history'?view==='history':view==='board'&&status===tab.value;return <button key={tab.label} className={selected?'is-selected':''} aria-pressed={selected} onClick={()=>{setView(tab.value==='history'?'history':'board');setStatus(tab.value==='history'?'':tab.value as ProductionStatus|'');reset();}}>{tab.label}</button>;})}</div>
  <div className="admin-toolbar admin-orders-toolbar"><label className="admin-search">Search orders<input type="search" placeholder="Find an order, customer, phone or pet…" value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></label><label>From date<input type="date" value={from} onChange={e=>{setFrom(e.target.value);reset();}}/></label><label>To date<input type="date" value={to} onChange={e=>{setTo(e.target.value);reset();}}/></label>{(from||to||search||status||view==='history')&&<button onClick={()=>{setFrom('');setTo('');setSearch('');setStatus('');setView('board');reset();}}>Clear filters</button>}<div className="admin-orders-sync"><button className="admin-orders-sync-chip" aria-label="Refresh orders" title={syncState==='issue'||error?'Sync issue · Click to sync now':lastUpdated?'Last synced at '+lastUpdated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · Click to sync now':'Click to sync now'} onClick={()=>setRefresh(n=>n+1)} disabled={moving||loading}><span aria-hidden="true">{syncState==='issue'||error?'⚠':'↻'}</span><span role="status" aria-label={loading||syncState==='syncing'?'Syncing orders':syncState==='issue'||error?'Sync issue':'Last orders update'}>{loading||syncState==='syncing'?'Syncing...':syncState==='issue'||error?'Sync issue':lastUpdated?.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})||'—'}</span></button></div></div>
  {error&&<p className="admin-error" role="alert">{error}</p>}
  {view==='board'&&!status&&<div className="admin-lane-controls"><button aria-label="Scroll lanes left" onClick={()=>document.getElementById('order-lanes')?.scrollBy({left:-360,behavior:'smooth'})}>←</button><span>Scroll to see more stages</span><button aria-label="Scroll lanes right" onClick={()=>document.getElementById('order-lanes')?.scrollBy({left:360,behavior:'smooth'})}>→</button></div>}
  {view==='history'?<div className="admin-horizontal-lanes admin-history-grid" aria-label="Order history">{columns.map(renderLane)}</div>:<><div id="order-lanes" className={status?"admin-filter-grid":"admin-lanes"} tabIndex={0} role="region" aria-label="Production lanes">{columns.filter(s=>s!=='delivered').map(renderLane)}</div>{columns.includes('delivered')&&<div className="admin-delivered-section admin-delivered-week">{renderLane('delivered')}</div>}</>}
  {opened&&<dialog ref={dialog} className="admin-order-dialog" aria-label="Order details" onCancel={e=>{e.preventDefault();setOpened(null);}}><div className="admin-modal-heading"><a href={'/admin/orders/'+opened}>Open full page</a><button onClick={()=>setOpened(null)} aria-label="Close order">Close ×</button></div><OrderDetail key={opened} id={opened} embedded/></dialog>}
  {cancel&&<CancelOrder code={cancel.order_code} busy={moving} error={error} onDismiss={()=>{setCancel(null);setError('');}} onConfirm={reason=>void move(cancel,'cancelled',reason)}/>}
 </>;
}
