import {ShippingLabel} from './ShippingLabel';
import {orderDate} from './orderDate';
import {useState,useRef,useCallback,useEffect} from 'react';
import {useSync} from '../ui/useSync';
import {admin} from '../data/adminBackend';
import {AdminError,nextStatuses,productionStatus,statusLabel,type ProductionDetail} from '../domain/admin';
import type {Order} from '../domain/model';
import {Downloads,DesignImage} from '../components';
import {getCollarSummary} from '../domain/presentation';
import {SnapshotLettering} from './SnapshotLettering';
import {AdminCollar} from './Collar';
import {CancelOrder} from './CancelOrder';
function errorText(error:unknown){const code=error instanceof AdminError?error.code:'PersistenceError';return ({Unauthorized:'Your account does not have administrative access.',OrderNotFound:'Order not found.',InvalidStatusTransition:'This status change is not allowed.',CatalogUnavailable:'This design is unavailable.',HeroConfigurationError:'Check the image configuration.',DriveSyncError:'Image sync is unavailable.',ShippingSetupRequired:'Apply the shipping-label Supabase migration before saving addresses.',PersistenceError:'Could not save or load. Please retry.',Conflict:'This record changed. Reload before saving again.'})[code];}
function Message({error}:{error:string}){return error?<p className="admin-error" role="alert">{error}</p>:null;}
function PageHeading({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="admin-page-heading">{eyebrow&&<p className="admin-eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>;}
function StatusBadge({status}:{status:Order['status']}){const value=productionStatus(status);return <span className={'admin-status status-'+value}>{statusLabel[value]}</span>;}
export function OrderDetail({id,embedded=false}:{id:string;embedded?:boolean}){
 const [data,setData]=useState<ProductionDetail|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[cancelling,setCancelling]=useState(false),[view,setView]=useState<'table'|'cards'>('table'),[collarIndex,setCollarIndex]=useState(0);
 const load=useCallback(async()=>{setBusy(true);setError('');try{const value=await admin.detail(id);setData(value);setNote(value.note);}catch(e){setError(errorText(e));}finally{setBusy(false);}},[id]);
 useEffect(()=>{void load();},[load]);
 const editing=useRef(false),saving=useRef(false);editing.current=!!data&&note!==data.note;saving.current=busy;
 const sync=useSync('orders',async()=>{if(saving.current)return;try{const value=await admin.detail(id);if(!editing.current)setNote(value.note);setData(previous=>previous&&Date.parse(previous.order.updated_at)>Date.parse(value.order.updated_at)?previous:value);setError('');}catch(e){setError(errorText(e));throw e;}});
 async function save(action:()=>Promise<ProductionDetail>,message:string){if(busy)return;setBusy(true);setFeedback('Saving…');setError('');try{const value=await action();setData(value);setFeedback(message);}catch(e){setError(errorText(e));setFeedback('');}finally{setBusy(false);}}
 const swipe=useRef<{x:number;y:number}|null>(null);
 const order=data?.order;
 return <>{!embedded&&<a className="admin-back" href="/admin/orders">← Orders</a>}<Message error={error}/>{!order?<div className="admin-empty"><p role="status">{busy||sync==='syncing'?'Loading order…':'Order unavailable.'}</p><button onClick={()=>void load().catch(()=>{})}>Retry</button></div>:<>
  <div className="admin-detail-heading"><PageHeading eyebrow="" title={order.order_code} description=""/><StatusBadge status={order.status}/></div>
  <div className={'admin-detail-layout'+(view==='cards'?' admin-detail-cards':'')}><div className="admin-production-collars"><div className="admin-collar-viewbar"><div className="admin-collar-heading"><h2>Collars</h2><span>{order.items.length}</span></div><div className="admin-view-switch" aria-label="Collar view"><button aria-pressed={view==='table'} className={view==='table'?'is-selected':''} onClick={()=>setView('table')}>Summary</button><button aria-pressed={view==='cards'} className={view==='cards'?'is-selected':''} onClick={()=>setView('cards')}>Cards</button></div>{view==='cards'&&<div className="admin-collar-pagination"><button aria-label="Previous collar" disabled={collarIndex===0} onClick={()=>setCollarIndex(i=>i-1)}>←</button><span aria-live="polite">{collarIndex+1} / {order.items.length}</span><button aria-label="Next collar" disabled={collarIndex>=order.items.length-1} onClick={()=>setCollarIndex(i=>i+1)}>→</button></div>}</div>{view==='table'?<div className={'admin-collar-accordion'+(order.items.length>4?' is-scrollable':'')}>{order.items.map((item,n)=>{const summary=getCollarSummary(item,'en');return <details key={item.id}><summary><DesignImage design={item.design} locale="en"/><div><small>COLLAR {n+1}</small><strong><SnapshotLettering font={item.font} name={item.pet_name} maximum={30}/></strong><span>{item.design.code} · {summary.sizeWidth} · {summary.fastening}</span></div><span className="admin-accordion-chevron" aria-hidden="true"></span></summary><AdminCollar item={item} number={n+1} compact/></details>;})}</div>:<div className="admin-swipe-card" onTouchStart={e=>{if(e.touches.length!==1|| (e.target as HTMLElement).closest('button,a,input,textarea,select')){swipe.current=null;return;}swipe.current={x:e.touches[0].clientX,y:e.touches[0].clientY};}} onTouchEnd={e=>{const start=swipe.current;swipe.current=null;if(!start||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)setCollarIndex(i=>Math.max(0,Math.min(order.items.length-1,i+(dx<0?1:-1))));}} onTouchCancel={()=>{swipe.current=null;}}><AdminCollar key={order.items[Math.min(collarIndex,order.items.length-1)].id} item={order.items[Math.min(collarIndex,order.items.length-1)]} number={Math.min(collarIndex,order.items.length-1)+1}/></div>}</div>
  <aside className="admin-workbench" aria-label="Production controls"><section className="admin-panel"><h2>Customer</h2><p className="admin-customer-name">{order.customer_snapshot.name}</p><p>{order.customer_snapshot.phone}</p><div className="admin-order-created"><span>Order placed</span><time dateTime={order.confirmed_at}>{orderDate(order.confirmed_at)}</time>{order.status==='delivered'&&<><span>Delivered</span>{data.deliveredAt?<time dateTime={data.deliveredAt}>{orderDate(data.deliveredAt)}</time>:<span>Date not recorded</span>}</>}</div></section>
   {order.status!=='cancelled'&&order.status!=='delivered'&&<section className="admin-panel"><h2>Actions</h2><div className="admin-status-actions">{nextStatuses(order.status).map(s=><button className={s==='cancelled'?'admin-cancel':'admin-primary'} key={s} disabled={busy} onClick={()=>s==='cancelled'?setCancelling(true):save(()=>admin.status(order,s),'Status updated')}>{s==='cancelled'?'Cancel order':'Move to '+statusLabel[s]}</button>)}</div><p className="admin-feedback" role="status">{feedback}</p>{error&&<button disabled={busy} onClick={load}>Reload saved version</button>}</section>}{['ready','delivered'].includes(productionStatus(order.status))&&<ShippingLabel order={order} onSave={async address=>{const updated=await admin.shipping(order,address);setData(current=>current?{...current,order:updated}:current);return updated;}}/>}
   {order.status==='cancelled'&&<section className="admin-panel"><h2>Cancellation reason</h2><p>{data.cancellationReason||'No reason provided.'}</p></section>}<section className="admin-panel admin-order-tools"><details className="admin-note-disclosure"><summary>Production note <span>{note!==data.note?'Unsaved':note.trim()?'Added':'Optional'}</span></summary><label>Internal note<textarea rows={3} placeholder="A detail to remember…" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><p className="admin-hint">For your team only.</p><button className="admin-primary" disabled={busy||note===data.note} onClick={()=>save(()=>admin.note(order,note),'Note saved')}>Save note</button></details><div className="admin-order-downloads"><h3>Order documents</h3><Downloads order={order} locale="en"/></div></section>
  </aside></div>{cancelling&&<CancelOrder code={order.order_code} busy={busy} error={error} onDismiss={()=>setCancelling(false)} onConfirm={reason=>void save(async()=>{const result=await admin.status(order,'cancelled',reason);setCancelling(false);return result;},'Order cancelled')}/>}</>}</>;
}

