import {useEffect,useState,type FormEvent} from 'react';
import {uploadImage} from '../data/adminBackend';
import {wovenGroups} from '../domain/catalogGroups';
export function Uploads({destination,onUploaded,categories=[],designType}:{destination?:'catalog'|'hero';onUploaded?:()=>void;categories?:string[];designType?:'woven'|'printed'}){
 const [target,setTarget]=useState<'catalog'|'hero'>(destination||'catalog'),[type,setType]=useState<'woven'|'printed'>(designType||'woven'),[group,setGroup]=useState('medium-large'),[code,setCode]=useState(''),[collection,setCollection]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;if(!file||busy)return;setBusy(true);setError('');setSaved('');try{await uploadImage(file,{target,type,group,code:code.trim().toUpperCase(),collection:collection.trim()});setFile(null);setCode('');setCollection('');setPreview('');form.reset();onUploaded?.();setSaved(target==='catalog'?code.trim().toUpperCase()+' uploaded. Activate it from Catalog when ready.':'Photo uploaded. Activate it from Hero when ready.');}catch(e){setError(e instanceof Error?e.message:'Could not upload. Please retry.');}finally{setBusy(false);}}
 return <div className="admin-upload-workspace"><div className="admin-upload-layout"><form onSubmit={submit} className="admin-upload-form">{!destination&&<div className="admin-view-tabs" aria-label="Upload destination">{(['catalog','hero'] as const).map(value=><button key={value} type="button" disabled={busy} aria-pressed={target===value} className={target===value?'is-selected':''} onClick={()=>{setTarget(value);setSaved('');setError('');}}>{value==='catalog'?'Catalog design':'Hero photo'}</button>)}</div>}<fieldset disabled={busy}><label className="admin-upload-drop">Choose an image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);setSaved('');setError('');}}/><span>JPG, PNG or WebP · Up to 10 MB</span></label>{target==='catalog'&&<><label>Design code<input required maxLength={40} pattern="[A-Za-z0-9][A-Za-z0-9_-]*" placeholder="For example, CH-50" value={code} onChange={e=>{setCode(e.target.value.toUpperCase());setSaved('');}}/></label>{!designType&&<label>Type<select value={type} onChange={e=>setType(e.target.value as 'woven'|'printed')}><option value="woven">Woven</option><option value="printed">Printed</option></select></label>}{type==='woven'?<label>Size group<select value={group} onChange={e=>setGroup(e.target.value)}>{wovenGroups.map(g=><option key={g.id} value={g.id}>{g.label} · {g.sizes.join(' / ')}</option>)}</select></label>:<label>Collection<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="">Choose a collection</option>{categories.map(name=><option key={name} value={name}>{name.charAt(0).toLocaleUpperCase('es')+name.slice(1)}</option>)}</select></label>}</>}</fieldset><p className="admin-upload-note">New images stay hidden until you activate them. Drive sync keeps these uploads.</p>{error&&<p className="admin-error" role="alert">{error}</p>}{saved&&<div className="admin-upload-success" role="status"><p>{saved}</p><a href={target==='catalog'?'/admin/catalog':'/admin/hero'}>Open {target==='catalog'?'Catalog':'Hero'}</a></div>}<button className="admin-primary" disabled={busy||!file||!!saved}>{busy?'Uploading…':'Upload image'}</button></form><aside className="admin-upload-preview">{preview?<img src={preview} alt="Selected image preview"/>:<div><span>Preview</span><p>Your image will appear here.</p></div>}</aside></div></div>;
}
