import {it,expect,vi} from 'vitest';
import {createAdminApplication,type AdminRepository} from './admin';
import type {Order} from '../domain/model';
function setup(owner=true){const repository={authorized:vi.fn(async()=>owner),list:vi.fn(async()=>[]),deliveredWeek:vi.fn(async()=>({orders:[],total:0})),detail:vi.fn(async()=>null),status:vi.fn(),note:vi.fn(),shipping:vi.fn(),catalog:vi.fn(),availability:vi.fn(),availabilityBatch:vi.fn(),hero:vi.fn(async()=>({revision:0,images:[]})),saveHero:vi.fn()} satisfies AdminRepository;return {repository,app:createAdminApplication(repository,{load:()=>[]})};}
it('denies every administrative operation before persistence',async()=>{const {app,repository}=setup(false);for(const operation of [()=>app.list('','',0),()=>app.detail('id'),()=>app.status({status:'new'} as Order,'in_progress'),()=>app.note({} as Order,'private'),()=>app.catalog(),()=>app.availability({designId:'id',width:0,enabled:false,revision:0}),()=>app.hero(),()=>app.saveHero({revision:0,images:[]})])await expect(operation()).rejects.toMatchObject({code:'Unauthorized'});expect(repository.list).not.toHaveBeenCalled();expect(repository.note).not.toHaveBeenCalled();});
it('normalizes search and page',async()=>{const {app,repository}=setup();await app.list('  ANA   Garcia  ','',-1);expect(repository.list).toHaveBeenCalledWith('ANA Garcia','',0,undefined);});
it('rejects invalid transition before repository',async()=>{const {app,repository}=setup();await expect(app.status({status:'cancelled'} as Order,'new')).rejects.toMatchObject({code:'InvalidStatusTransition'});expect(repository.status).not.toHaveBeenCalled();});
it('only saves a complete postal address on ready or delivered orders',async()=>{const address={line1:'Av. República 123',line2:'',city:'Quito',region:'Pichincha',postalCode:'170135',country:'Ecuador'};const {app,repository}=setup();await expect(app.shipping({status:'in_progress'} as Order,address)).rejects.toMatchObject({code:'PersistenceError'});await expect(app.shipping({status:'ready'} as Order,{...address,line1:' '})).rejects.toMatchObject({code:'PersistenceError'});expect(repository.shipping).not.toHaveBeenCalled();await app.shipping({id:'o',status:'ready'} as Order,address);expect(repository.shipping).toHaveBeenCalledWith({id:'o',status:'ready'},address);});
it('identifies an unapplied shipping-label RPC migration',async()=>{const {app,repository}=setup();repository.shipping.mockRejectedValueOnce(new Error('PGRST202: Could not find the function public.admin_save_shipping_address in the schema cache'));await expect(app.shipping({id:'o',status:'ready'} as Order,{line1:'Street',line2:'',city:'Quito',region:'',postalCode:'',country:'Ecuador'})).rejects.toMatchObject({code:'ShippingSetupRequired'});});
it('returns explicit missing order error',async()=>{await expect(setup().app.detail('missing')).rejects.toMatchObject({code:'OrderNotFound'});});
it('protects note limits and duplicate hero entries',async()=>{const {app,repository}=setup();await expect(app.note({} as Order,'x'.repeat(4001))).rejects.toMatchObject({code:'PersistenceError'});await expect(app.saveHero({revision:0,images:[{id:'x',active:true},{id:'x',active:true}]})).rejects.toMatchObject({code:'HeroConfigurationError'});expect(repository.note).not.toHaveBeenCalled();expect(repository.saveHero).not.toHaveBeenCalled();});
it('maps provider conflicts without leaking raw diagnostics',async()=>{const {app,repository}=setup();repository.list.mockRejectedValueOnce(new Error('STATE_CONFLICT secret diagnostics'));await expect(app.list('','',0)).rejects.toMatchObject({code:'Conflict',message:'Conflict'});});

it('bulk availability checks access, duplicates and submits one repository operation',async()=>{const change={designId:'design',width:0,enabled:false,revision:0};await expect(setup(false).app.availabilityBatch([change])).rejects.toMatchObject({code:'Unauthorized'});const {app,repository}=setup();await expect(app.availabilityBatch([change,change])).rejects.toMatchObject({code:'PersistenceError'});expect(repository.availabilityBatch).not.toHaveBeenCalled();await app.availabilityBatch([change,{...change,width:2.5}]);expect(repository.availabilityBatch).toHaveBeenCalledTimes(1);expect(repository.availability).not.toHaveBeenCalled();});

it('validates date ranges and private cancellation reason',async()=>{const {app,repository}=setup();await expect(app.list('','',0,{from:'invalid'})).rejects.toMatchObject({code:'PersistenceError'});await expect(app.list('','',0,{from:'2026-10-04',to:'2026-10-03'})).rejects.toMatchObject({code:'PersistenceError'});expect(repository.list).not.toHaveBeenCalled();await app.list('','new',0,{from:'2026-10-03',to:'2026-10-04'});expect(repository.list).toHaveBeenCalledWith('','new',0,{from:'2026-10-03',to:'2026-10-04'});await expect(app.status({status:'new'} as Order,'cancelled','x'.repeat(1001))).rejects.toMatchObject({code:'PersistenceError'});await expect(app.status({status:'new'} as Order,'in_progress','reason')).rejects.toMatchObject({code:'PersistenceError'});expect(repository.status).not.toHaveBeenCalled();await app.status({status:'new'} as Order,'cancelled','  requested  ');expect(repository.status).toHaveBeenCalledWith({status:'new'},'cancelled','requested');});

it('rejects invalid size/width pairs before persistence and distinguishes shared widths',async()=>{const {app,repository}=setup();const change={designId:'design',size:'M',width:3,enabled:true,revision:0};await expect(app.availability(change)).rejects.toMatchObject({code:'PersistenceError'});expect(repository.availability).not.toHaveBeenCalled();await app.availabilityBatch([{...change,size:'M',width:2.5},{...change,size:'ML',width:2.5}]);expect(repository.availabilityBatch).toHaveBeenCalledTimes(1);});
