import NeuteredIcon from './ui/NeuteredIcon';
import {Accordion,AccordionItem} from './ui/Accordion';
import DecorationOptions from './DecorationOptions';
import {selectPersonalization,selectNameDecoration} from './domain/personalization';
export {validPersonality} from './domain/personalization';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {Item,Locale,Personalization,FontRecord} from './domain/model';
const symbols={heart:'M12 21S2 15 2 8a5 5 0 0 1 10-2 5 5 0 0 1 10 2c0 7-10 13-10 13Z',paw:'M7 13c-4 4-2 8 5 7 7 1 9-3 5-7-3-4-7-4-10 0ZM5 5a2 3 0 1 0 0 6 2 3 0 1 0 0-6ZM11 2a2 3 0 1 0 0 6 2 3 0 1 0 0-6ZM18 4a2 3 0 1 0 0 6 2 3 0 1 0 0-6Z',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',flower:'M12 8c-7-10-13 0-6 4-7 5 0 13 6 5 7 8 13 0 6-5 7-4 1-14-6-4ZM10 12a2 2 0 1 0 4 0 2 2 0 1 0-4 0',bone:'M7 8c-5-8-10 0-5 4-5 4 0 12 5 4h10c5 8 10 0 5-4 5-4 0-12-5-4Z',crown:'m2 6 5 5 5-8 5 8 5-5-3 14H5Z'};
export function Icon({kind}:{kind:string}){if(kind==='neutered')return <NeuteredIcon/>;return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round"><path d={kind==='drawing'?'m4 18 1-5L17 1l5 5-12 12-6 1ZM14 4l5 5':kind==='dog_photo'?'M3 5h18v16H3ZM8 5l2-3h4l2 3M8 13a4 4 0 1 0 8 0 4 4 0 1 0-8 0':kind==='none'?'M5 6h14M5 12h14M5 18h9':({user:'M12 12a4 4 0 1 0 0-8 4 4 0 1 0 0 8ZM4 21v-2a8 8 0 0 1 16 0v2Z',phone:'M5 2h4l2 6-3 2c2 3 3 4 6 6l2-3 6 2v4c-9 5-24-10-17-17Z',address:'M12 22S4 13 4 8a8 8 0 0 1 16 0c0 5-8 14-8 14ZM9 8a3 3 0 1 0 6 0 3 3 0 1 0-6 0',email:'M2 5h20v14H2ZM2 5l10 8L22 5',neutered:'M9 2h6v7h7v6h-7v7H9v-7H2V9h7Z'} as Record<string,string>)[kind]||symbols[kind as keyof typeof symbols]||symbols.star}/></svg>}
export default function PersonalityOptions({item,locale,busy,onChange,children,font}:{item:Item;locale:Locale;busy:boolean;onChange:(p:Partial<Item>)=>void;children:(type:Personalization)=>ReactNode;font?:FontRecord}){
 const [reset,setReset]=useState(0),[mediaClose,setMediaClose]=useState({drawing:0,dog_photo:0});
 const previousMedia=useRef(item.personalization_type);
 useEffect(()=>{
  if(previousMedia.current!==item.personalization_type){
   if(item.personalization_type==='drawing')setMediaClose(v=>({...v,dog_photo:v.dog_photo+1}));
   if(item.personalization_type==='dog_photo')setMediaClose(v=>({...v,drawing:v.drawing+1}));
   previousMedia.current=item.personalization_type;
  }
 },[item.personalization_type]);
 const es=locale==='es';const labels={decoration:es?'Decoración':'Decoration',drawing:es?'Dibujo':'Drawing',dog_photo:es?'Foto':'Photo',none:es?'Sin personalización':'No personalization'};
 const descriptions={decoration:es?'Agrega pequeños iconos para personalizar su placa.':"Add small icons to personalize your pet's tag.",drawing:es?'Un dibujo lineal de su raza o algo que te guste.':'A line drawing of your pet’s breed or something you like.',dog_photo:es?'Agrega una foto de tu mascota para grabar.':'Add a photo of your pet to be engraved.',none:es?'Solo texto en la placa.':'Keep the tag with text only.'};
 return <Accordion className="personality-options">{(['decoration','drawing','dog_photo','none'] as Personalization[]).map(type=>{const active=type==='decoration'?(item.personalization_type==='decoration'||!!item.decorationIcon||!!item.informationIcons?.length):item.personalization_type===type;const heading=<><Icon kind={type}/><span><strong>{labels[type]}</strong><small>{descriptions[type]}</small></span></>;return type==='none'?<section key={type} className={`personality-option ${active?'selected':''}`}><button type="button" disabled={busy} className="personality-toggle" id="personality-toggle-none" aria-pressed={active} onClick={()=>{setReset(v=>v+1);onChange({personalization_type:type,decorationIcon:undefined,informationIcons:[],personalization_notes:'',attachments:[]});}}>{heading}</button></section>:<AccordionItem key={type} id={type} heading={heading} selected={active} disabled={busy} initialOpen={active} onOpen={type==='decoration'?()=>onChange(selectNameDecoration(item,item.decorationIcon)):undefined} closeToken={reset+(type==='drawing'||type==='dog_photo'?mediaClose[type]:0)}>
 {type==='decoration'?<DecorationOptions item={item} locale={locale} onChange={onChange} font={font} icon={kind=><Icon kind={kind}/>}/>:<><p>{es?(type==='drawing'?'Sube una referencia para el dibujo lineal que se grabará en la placa.':'Sube una foto nítida para preparar el grabado.'):(type==='drawing'?'Upload a reference for the line drawing to be engraved on the tag.':'Upload a clear pet photo to prepare for engraving.')}</p><div className="engraving-upload-layout">{!item.attachments.some(a=>a.purpose===type)&&<figure className="engraving-example"><img src={import.meta.env.BASE_URL+'examples/'+(type==='drawing'?'drawing':'photo')+'.svg'} alt={es?(type==='drawing'?'Ejemplo de placa con ilustración lineal':'Ejemplo de placa con fotografía grabada'):(type==='drawing'?'Example tag with a line drawing':'Example tag with an engraved photo')} loading="lazy"/><figcaption>{es?'Ejemplo de grabado':'Engraving example'}</figcaption></figure>}{children(type)}</div><label className="personality-notes">{es?'Indicaciones opcionales':'Optional instructions'}<textarea rows={2} maxLength={2000} value={active?item.personalization_notes:''} onChange={e=>onChange({...selectPersonalization(item,type),personalization_notes:e.target.value})}/></label></>}

 </AccordionItem>})}</Accordion>;
}
